from datetime import date
import time
from faker import Faker
from openpyxl import load_workbook
from selenium.webdriver import Keys
from selenium import webdriver
from selenium.webdriver.common.by import By
from webdriver_manager.chrome import ChromeDriverManager
from Locators.PatientLocators import PatientLocators
from Locators.PracticeLocators import PracticeLocators
from Locators.Locators import Locators
from selenium.webdriver import ActionChains

FilePath = "C:/Users/Administrator/PycharmProject/LegrandePython/TestData/Data.xlsx"
datafile = load_workbook(FilePath)
testData = datafile['Test Data']
loginData = datafile["Login Credentials"]
scriptData = datafile["Script Data"]

faker = Faker()
today = date.today()
currentDate = today.strftime("%m/%d/%Y")
FirstName = faker.first_name()
LastName = faker.last_name()
PhoneNumber = faker.phone_number()
EmailAddress = FirstName + "." + LastName + "@mailinator.com"


class CommanFlow:
    def __init__(self, driver):
        self.driver = driver

    def CreatePatient(self):
        self.driver.find_element_by_class_name(PracticeLocators.addPersonButton).click()
        self.driver.find_element_by_name(PracticeLocators.firstName).send_keys(FirstName)
        self.driver.find_element_by_name(PracticeLocators.lastName).send_keys(LastName)
        self.driver.find_element_by_name(PracticeLocators.birthDate).send_keys(currentDate)
        self.driver.find_element_by_name(PracticeLocators.phoneNumber).send_keys(PhoneNumber)
        self.driver.find_element_by_name(Locators.Email).send_keys(EmailAddress.lower())
        self.driver.find_element_by_xpath(PracticeLocators.createAccountButton).click()
        time.sleep(5)
        if "Congratulations, you have successfully created a new Patient Account." in self.driver.page_source:
            self.driver.find_element_by_xpath(PracticeLocators.closeButton).click()
            testData.cell(2, 1).value = FirstName + " " + LastName
            testData.cell(2, 2).value = FirstName + " " + LastName + " (" + currentDate + ")"
            loginData.cell(8, 3).value = EmailAddress.lower()
            datafile.save(FilePath)
            print("\nPatient Created Successfully")
        else:
            print("\nPatient not Created")
        self.driver.close()

    def CreateUser(self):
        self.driver.find_element_by_class_name(PracticeLocators.accountLinkLabel).click()
        self.driver.find_element_by_link_text(PracticeLocators.manageUser).click()
        self.driver.find_element_by_xpath(PracticeLocators.addUserButton).click()
        self.driver.find_element_by_name(PracticeLocators.firstName).send_keys(FirstName)
        self.driver.find_element_by_name(PracticeLocators.lastName).send_keys(LastName)
        self.driver.find_element_by_name(Locators.Email).send_keys(EmailAddress.lower())
        self.driver.find_element_by_name(PracticeLocators.phoneNumber).send_keys(PhoneNumber)
        self.driver.find_element_by_class_name(PracticeLocators.selectAccountType).click()
        time.sleep(2)
        self.driver.find_element_by_xpath(PracticeLocators.clerkOption).click()
        time.sleep(1)
        self.driver.find_element_by_xpath(PracticeLocators.createAccountButton).click()
        time.sleep(3)
        if "Congratulations. You have successfully created new user profile." in self.driver.page_source:
            self.driver.find_element_by_xpath(PracticeLocators.dismissButton).click()
            print("User created successfully")
        else:
            print("User not created")
        self.driver.close()

    def PatientMainSearch(self):
        self.driver.find_element_by_class_name(PracticeLocators.mainPatientSearch).click()
        self.driver.find_element_by_xpath(PracticeLocators.mainSearchTextbox).send_keys(testData.cell(2, 1).value)
        self.driver.find_element_by_class_name(PracticeLocators.mainSearchButton).click()
        try:
            self.driver.find_element_by_xpath(PracticeLocators.tableRow).click()
            try:
                self.driver.find_element_by_link_text(PracticeLocators.viewDetails).click()
            except:
                print("\nOrder not created for " + testData.cell(2, 1).value + ".")
        except:
            print("\nPatient: " + testData.cell(2, 1).value + " not found...")
        self.driver.close()

    def ChangeProductPrice(self):
        self.driver.find_element_by_class_name(PracticeLocators.accountLinkLabel).click()
        self.driver.find_element_by_link_text(Locators.productList).click()
        time.sleep(2)
        self.driver.find_element_by_xpath(PracticeLocators.tableRow).click()
        self.driver.find_element_by_xpath(Locators.updateButton).click()
        self.driver.find_element_by_xpath(Locators.changePriceButton).click()
        if "You have successfully updated the price of 100 Compound" in self.driver.page_source:
            self.driver.find_element_by_xpath(PracticeLocators.closeButton).click()
            print('\nProduct price changed successfully')
        else:
            print('\nProduct price not changed')
        self.driver.close()

    def OnetimeRXSkipPayment(self):
        self.driver.implicitly_wait(20)
        self.driver.find_element_by_class_name(PracticeLocators.Add_RX).click()
        PatientSearch = self.driver.find_element_by_xpath(PracticeLocators.Patient_search_textbox)
        PatientSearch.click()
        PatientSearch.send_keys(testData.cell(2, 1).value)
        self.driver.find_element_by_xpath("(//*[text()='" + testData.cell(2, 2).value + "'])[1]").click()
        DoctorSearch = self.driver.find_element_by_xpath(PracticeLocators.doctor_search_textbox)
        DoctorSearch.click()
        DoctorSearch.send_keys(scriptData.cell(2, 8).value)
        self.driver.find_element_by_xpath(
            "(//*[text()='" + scriptData.cell(2, 8).value + " " + "Practice'])[2]").click()
        self.driver.find_element_by_xpath(PracticeLocators.NextButton).click()
        self.driver.find_element_by_xpath(PracticeLocators.CreateOnetimeRXButton).click()
        self.driver.find_element_by_name(PracticeLocators.OnetimeSearchMedicine).send_keys(scriptData.cell(2, 1).value)
        time.sleep(2)
        self.driver.find_element_by_xpath("//*[text()='" + scriptData.cell(2, 1).value + "']").click()
        self.driver.find_element_by_xpath(PracticeLocators.AddButton).click()
        self.driver.find_element_by_xpath(PracticeLocators.ProductQuantity).click()
        time.sleep(1)
        self.driver.find_element_by_xpath(PracticeLocators.Quantity).click()
        # self.driver.find_element_by_xpath(PracticeLocators.ProductRefilles).click()
        # time.sleep(1)
        # self.driver.find_element_by_xpath(PracticeLocators.Quantity).click()
        # time.sleep(2)
        # self.driver.find_element_by_xpath(PracticeLocators.DAWCheckbox).click()
        # time.sleep(2)
        # instruction = self.driver.find_element_by_xpath(PracticeLocators.productInstruction)
        # instruction.click()
        # instruction.send_keys(testData.cell(2, 3).value)
        # self.driver.find_element_by_xpath(PracticeLocators.allergiesButton).click()
        # allergies = self.driver.find_element_by_xpath(PracticeLocators.allergiesTextbox)
        # allergies.clear()
        # allergies.send_keys(testData.cell(2, 4).value)
        # self.driver.find_element_by_xpath(PracticeLocators.doneButton).click()
        # self.driver.find_element_by_xpath(PracticeLocators.addDropchartButton).click()
        # time.sleep(2)
        # element = self.driver.find_element_by_xpath(PracticeLocators.selectDocuments)
        # self.driver.execute_script("arguments[0].click()", element)
        # self.driver.find_element_by_xpath(PracticeLocators.selectButton).click()
        self.driver.find_element_by_xpath(PracticeLocators.skipPayment).click()
        self.driver.find_element_by_xpath(PracticeLocators.surgeryDate).send_keys(currentDate)
        # Notes = self.driver.find_elements(By.XPATH, PracticeLocators.pharmacyNotes)
        # if Notes:
        #     Notes[0].send_keys(testData.cell(2, 5).value)
        # else:
        #     self.driver.find_element_by_xpath(Locators.addNoteButton).click()
        #     self.driver.find_element_by_xpath('//textarea[@class="sc-hIVACf cpAwkS"]').send_keys(testData.cell(2, 5).value)
        #     pharmaCheckbox = self.driver.find_elements(By.XPATH, "//label[contains(text(),'Pharmacy')]")
        #     if pharmaCheckbox:
        #         pharmaCheckbox[0].click()
        #     self.driver.find_element_by_xpath(PatientLocators.iframeSaveButton).click()
        createOrderButton = self.driver.find_element_by_xpath(PracticeLocators.submit_CreateOrderButton)
        self.driver.execute_script("arguments[0].click()", createOrderButton)
        time.sleep(7)

    def OnetimeOTCSkipPayment(self):
        self.driver.find_element_by_class_name(PracticeLocators.Add_RX).click()
        PatientSearch = self.driver.find_element_by_xpath(PracticeLocators.Patient_search_textbox)
        PatientSearch.click()
        PatientSearch.send_keys(testData.cell(2, 1).value)
        self.driver.find_element_by_xpath("(//*[text()='" + testData.cell(2, 2).value + "'])[1]").click()
        DoctorSearch = self.driver.find_element_by_xpath(PracticeLocators.doctor_search_textbox)
        DoctorSearch.click()
        DoctorSearch.send_keys(scriptData.cell(2, 8).value)
        self.driver.find_element_by_xpath(
            "(//*[text()='" + scriptData.cell(2, 8).value + " " + "Practice'])[2]").click()
        self.driver.find_element_by_xpath(PracticeLocators.NextButton).click()
        self.driver.find_element_by_xpath(PracticeLocators.CreateOnetimeRXButton).click()
        self.driver.find_element_by_name(PracticeLocators.OnetimeSearchMedicine).send_keys(scriptData.cell(2, 2).value)
        time.sleep(2)
        self.driver.find_element_by_xpath("//*[text()='" + scriptData.cell(2, 2).value + "']").click()
        self.driver.find_element_by_xpath(PracticeLocators.AddButton).click()
        self.driver.find_element_by_xpath(PracticeLocators.ProductQuantity).click()
        time.sleep(1)
        self.driver.find_element_by_xpath(PracticeLocators.Quantity).click()
        self.driver.find_element_by_xpath(PracticeLocators.ProductRefilles).click()
        time.sleep(1)
        self.driver.find_element_by_xpath(PracticeLocators.Quantity).click()
        time.sleep(2)
        self.driver.find_element_by_xpath(PracticeLocators.DAWCheckbox).click()
        time.sleep(2)
        instruction = self.driver.find_element_by_xpath(PracticeLocators.productInstruction)
        instruction.click()
        instruction.send_keys(testData.cell(2, 3).value)
        self.driver.find_element_by_xpath(PracticeLocators.allergiesButton).click()
        allergies = self.driver.find_element_by_xpath(PracticeLocators.allergiesTextbox)
        allergies.clear()
        allergies.send_keys(testData.cell(2, 4).value)
        self.driver.find_element_by_xpath(PracticeLocators.doneButton).click()
        self.driver.find_element_by_xpath(PracticeLocators.addDropchartButton).click()
        time.sleep(2)
        element = self.driver.find_element_by_xpath(PracticeLocators.selectDocuments)
        self.driver.execute_script("arguments[0].click()", element)
        self.driver.find_element_by_xpath(PracticeLocators.selectButton).click()
        self.driver.find_element_by_xpath(PracticeLocators.skipPayment).click()
        self.driver.find_element_by_xpath(PracticeLocators.surgeryDate).send_keys(currentDate)
        Notes = self.driver.find_elements(By.XPATH, PracticeLocators.pharmacyNotes)
        if Notes:
            Notes[0].send_keys(testData.cell(2, 5).value)
        else:
            self.driver.find_element_by_xpath(PracticeLocators.addNoteButton).click()
            self.driver.find_element_by_xpath('//textarea[@class="sc-hIVACf cpAwkS"]').send_keys(
                testData.cell(2, 5).value)
            pharmaCheckbox = self.driver.find_elements(By.XPATH, "//label[contains(text(),'Pharmacy')]")
            if pharmaCheckbox:
                pharmaCheckbox[0].click()
            self.driver.find_element_by_xpath(PatientLocators.iframeSaveButton).click()
        createOrderButton = self.driver.find_element_by_xpath(PracticeLocators.submit_CreateOrderButton)
        self.driver.execute_script("arguments[0].click()", createOrderButton)
        time.sleep(7)

    def OnetimeCompoundSkipPayment(self):
        self.driver.find_element_by_class_name(PracticeLocators.Add_RX).click()
        PatientSearch = self.driver.find_element_by_xpath(PracticeLocators.Patient_search_textbox)
        PatientSearch.click()
        PatientSearch.send_keys(testData.cell(2, 1).value)
        self.driver.find_element_by_xpath("(//*[text()='" + testData.cell(2, 2).value + "'])[1]").click()
        DoctorSearch = self.driver.find_element_by_xpath(PracticeLocators.doctor_search_textbox)
        DoctorSearch.click()
        DoctorSearch.send_keys(scriptData.cell(2, 8).value)
        self.driver.find_element_by_xpath(
            "(//*[text()='" + scriptData.cell(2, 8).value + " " + "Practice'])[2]").click()
        self.driver.find_element_by_xpath(PracticeLocators.NextButton).click()
        self.driver.find_element_by_xpath(PracticeLocators.CreateOnetimeRXButton).click()
        self.driver.find_element_by_name(PracticeLocators.OnetimeSearchMedicine).send_keys(scriptData.cell(2, 3).value)
        time.sleep(2)
        self.driver.find_element_by_xpath("//*[text()='" + scriptData.cell(2, 3).value + "']").click()
        self.driver.find_element_by_xpath(PracticeLocators.AddButton).click()
        self.driver.find_element_by_xpath(PracticeLocators.ProductQuantity).click()
        time.sleep(1)
        self.driver.find_element_by_xpath(PracticeLocators.Quantity).click()
        self.driver.find_element_by_xpath(PracticeLocators.ProductRefilles).click()
        time.sleep(1)
        self.driver.find_element_by_xpath(PracticeLocators.Quantity).click()
        time.sleep(2)
        self.driver.find_element_by_xpath(PracticeLocators.DAWCheckbox).click()
        time.sleep(2)
        instruction = self.driver.find_element_by_xpath(PracticeLocators.productInstruction)
        instruction.click()
        instruction.send_keys(testData.cell(2, 3).value)
        self.driver.find_element_by_xpath(PracticeLocators.allergiesButton).click()
        allergies = self.driver.find_element_by_xpath(PracticeLocators.allergiesTextbox)
        allergies.clear()
        allergies.send_keys(testData.cell(2, 4).value)
        self.driver.find_element_by_xpath(PracticeLocators.doneButton).click()
        self.driver.find_element_by_xpath(PracticeLocators.addDropchartButton).click()
        time.sleep(2)
        element = self.driver.find_element_by_xpath(PracticeLocators.selectDocuments)
        self.driver.execute_script("arguments[0].click()", element)
        self.driver.find_element_by_xpath(PracticeLocators.selectButton).click()
        self.driver.find_element_by_xpath(PracticeLocators.skipPayment).click()
        self.driver.find_element_by_xpath(PracticeLocators.surgeryDate).send_keys(currentDate)
        Notes = self.driver.find_elements(By.XPATH, PracticeLocators.pharmacyNotes)
        if Notes:
            Notes[0].send_keys(testData.cell(2, 5).value)
        else:
            self.driver.find_element_by_xpath(PracticeLocators.addNoteButton).click()
            self.driver.find_element_by_xpath('//textarea[@class="sc-hIVACf cpAwkS"]').send_keys(
                testData.cell(2, 5).value)
            pharmaCheckbox = self.driver.find_elements(By.XPATH, "//label[contains(text(),'Pharmacy')]")
            if pharmaCheckbox:
                pharmaCheckbox[0].click()
            self.driver.find_element_by_xpath(PatientLocators.iframeSaveButton).click()
        createOrderButton = self.driver.find_element_by_xpath(PracticeLocators.submit_CreateOrderButton)
        self.driver.execute_script("arguments[0].click()", createOrderButton)
        time.sleep(7)

    def SubscriptionRXSkipPayment(self):
        self.driver.find_element_by_class_name(PracticeLocators.Add_RX).click()
        PatientSearch = self.driver.find_element_by_xpath(PracticeLocators.Patient_search_textbox)
        PatientSearch.click()
        PatientSearch.send_keys(testData.cell(2, 1).value)
        self.driver.find_element_by_xpath("(//*[text()='" + testData.cell(2, 2).value + "'])[1]").click()
        DoctorSearch = self.driver.find_element_by_xpath(PracticeLocators.doctor_search_textbox)
        DoctorSearch.click()
        DoctorSearch.send_keys(scriptData.cell(2, 8).value)
        self.driver.find_element_by_xpath(
            "(//*[text()='" + scriptData.cell(2, 8).value + " " + "Practice'])[2]").click()
        self.driver.find_element_by_xpath(PracticeLocators.NextButton).click()
        el = self.driver.find_element_by_xpath(PracticeLocators.createSubscriptionRxButton)
        self.driver.execute_script('arguments[0].click()', el)
        self.driver.find_element_by_xpath(PracticeLocators.subscriptionProductSearch).send_keys(scriptData.cell(2, 1).value)
        time.sleep(2)
        self.driver.find_element_by_xpath("//*[text()='" + scriptData.cell(2, 1).value + "']").click()
        self.driver.find_element_by_xpath(PracticeLocators.AddButton).click()
        self.driver.find_element_by_xpath(PracticeLocators.ProductQuantity).click()
        time.sleep(1)
        self.driver.find_element_by_xpath(PracticeLocators.Quantity).click()
        self.driver.find_element_by_xpath(PracticeLocators.ProductRefilles).click()
        time.sleep(1)
        self.driver.find_element_by_xpath(PracticeLocators.Quantity).click()
        time.sleep(2)
        self.driver.find_element_by_xpath(PracticeLocators.DAWCheckbox).click()
        time.sleep(2)
        instruction = self.driver.find_element_by_xpath(PracticeLocators.productInstruction)
        instruction.click()
        instruction.send_keys(testData.cell(2, 3).value)
        self.driver.find_element_by_xpath(PracticeLocators.allergiesButton).click()
        allergies = self.driver.find_element_by_xpath(PracticeLocators.allergiesTextbox)
        allergies.clear()
        allergies.send_keys(testData.cell(2, 4).value)
        self.driver.find_element_by_xpath(PracticeLocators.doneButton).click()
        self.driver.find_element_by_xpath(PracticeLocators.addDropchartButton).click()
        time.sleep(2)
        element = self.driver.find_element_by_xpath(PracticeLocators.selectDocuments)
        self.driver.execute_script("arguments[0].click()", element)
        self.driver.find_element_by_xpath(PracticeLocators.selectButton).click()
        self.driver.find_element_by_xpath(PracticeLocators.skipPayment).click()
        self.driver.find_element_by_xpath(PracticeLocators.surgeryDate).send_keys(currentDate)
        Notes = self.driver.find_elements(By.XPATH, PracticeLocators.pharmacyNotes)
        if Notes:
            Notes[0].send_keys(testData.cell(2, 5).value)
        else:
            self.driver.find_element_by_xpath(PracticeLocators.addNoteButton).click()
            self.driver.find_element_by_xpath('//textarea[@class="sc-hIVACf cpAwkS"]').send_keys(
                testData.cell(2, 5).value)
            pharmaCheckbox = self.driver.find_elements(By.XPATH, "//label[contains(text(),'Pharmacy')]")
            if pharmaCheckbox:
                pharmaCheckbox[0].click()
            self.driver.find_element_by_xpath(PatientLocators.iframeSaveButton).click()
        createOrderButton = self.driver.find_element_by_xpath(PracticeLocators.submit_CreateOrderButton)
        self.driver.execute_script("arguments[0].click()", createOrderButton)
        time.sleep(7)

    def SubscriptionOTCSkipPayment(self):
        self.driver.find_element_by_class_name(PracticeLocators.Add_RX).click()
        PatientSearch = self.driver.find_element_by_xpath(PracticeLocators.Patient_search_textbox)
        PatientSearch.click()
        PatientSearch.send_keys(testData.cell(2, 1).value)
        self.driver.find_element_by_xpath("(//*[text()='" + testData.cell(2, 2).value + "'])[1]").click()
        DoctorSearch = self.driver.find_element_by_xpath(PracticeLocators.doctor_search_textbox)
        DoctorSearch.click()
        DoctorSearch.send_keys(scriptData.cell(2, 8).value)
        self.driver.find_element_by_xpath(
            "(//*[text()='" + scriptData.cell(2, 8).value + " " + "Practice'])[2]").click()
        self.driver.find_element_by_xpath(PracticeLocators.NextButton).click()
        el = self.driver.find_element_by_xpath(PracticeLocators.createSubscriptionRxButton)
        self.driver.execute_script('arguments[0].click()', el)
        self.driver.find_element_by_xpath(PracticeLocators.subscriptionProductSearch).send_keys(scriptData.cell(2, 2).value)
        time.sleep(2)
        self.driver.find_element_by_xpath("//*[text()='" + scriptData.cell(2, 2).value + "']").click()
        self.driver.find_element_by_xpath(PracticeLocators.AddButton).click()
        self.driver.find_element_by_xpath(PracticeLocators.ProductQuantity).click()
        time.sleep(1)
        self.driver.find_element_by_xpath(PracticeLocators.Quantity).click()
        self.driver.find_element_by_xpath(PracticeLocators.ProductRefilles).click()
        time.sleep(1)
        self.driver.find_element_by_xpath(PracticeLocators.Quantity).click()
        time.sleep(2)
        self.driver.find_element_by_xpath(PracticeLocators.DAWCheckbox).click()
        time.sleep(2)
        instruction = self.driver.find_element_by_xpath(PracticeLocators.productInstruction)
        instruction.click()
        instruction.send_keys(testData.cell(2, 3).value)
        self.driver.find_element_by_xpath(PracticeLocators.allergiesButton).click()
        allergies = self.driver.find_element_by_xpath(PracticeLocators.allergiesTextbox)
        allergies.clear()
        allergies.send_keys(testData.cell(2, 4).value)
        self.driver.find_element_by_xpath(PracticeLocators.doneButton).click()
        self.driver.find_element_by_xpath(PracticeLocators.addDropchartButton).click()
        time.sleep(2)
        element = self.driver.find_element_by_xpath(PracticeLocators.selectDocuments)
        self.driver.execute_script("arguments[0].click()", element)
        self.driver.find_element_by_xpath(PracticeLocators.selectButton).click()
        self.driver.find_element_by_xpath(PracticeLocators.skipPayment).click()
        self.driver.find_element_by_xpath(PracticeLocators.surgeryDate).send_keys(currentDate)
        Notes = self.driver.find_elements(By.XPATH, PracticeLocators.pharmacyNotes)
        if Notes:
            Notes[0].send_keys(testData.cell(2, 5).value)
        else:
            self.driver.find_element_by_xpath(PracticeLocators.addNoteButton).click()
            self.driver.find_element_by_xpath('//textarea[@class="sc-hIVACf cpAwkS"]').send_keys(
                testData.cell(2, 5).value)
            pharmaCheckbox = self.driver.find_elements(By.XPATH, "//label[contains(text(),'Pharmacy')]")
            if pharmaCheckbox:
                pharmaCheckbox[0].click()
            self.driver.find_element_by_xpath(PatientLocators.iframeSaveButton).click()
        createOrderButton = self.driver.find_element_by_xpath(PracticeLocators.submit_CreateOrderButton)
        self.driver.execute_script("arguments[0].click()", createOrderButton)
        time.sleep(7)

    def SubscriptionCompoundSkipPayment(self):
        self.driver.find_element_by_class_name(PracticeLocators.Add_RX).click()
        PatientSearch = self.driver.find_element_by_xpath(PracticeLocators.Patient_search_textbox)
        PatientSearch.click()
        PatientSearch.send_keys(testData.cell(2, 1).value)
        self.driver.find_element_by_xpath("(//*[text()='" + testData.cell(2, 2).value + "'])[1]").click()
        DoctorSearch = self.driver.find_element_by_xpath(PracticeLocators.doctor_search_textbox)
        DoctorSearch.click()
        DoctorSearch.send_keys(scriptData.cell(2, 8).value)
        self.driver.find_element_by_xpath(
            "(//*[text()='" + scriptData.cell(2, 8).value + " " + "Practice'])[2]").click()
        self.driver.find_element_by_xpath(PracticeLocators.NextButton).click()
        el = self.driver.find_element_by_xpath(PracticeLocators.createSubscriptionRxButton)
        self.driver.execute_script('arguments[0].click()', el)
        self.driver.find_element_by_xpath(PracticeLocators.subscriptionProductSearch).send_keys(scriptData.cell(2, 3).value)
        time.sleep(2)
        self.driver.find_element_by_xpath("//*[text()='" + scriptData.cell(2, 3).value + "']").click()
        self.driver.find_element_by_xpath(PracticeLocators.AddButton).click()
        self.driver.find_element_by_xpath(PracticeLocators.ProductQuantity).click()
        time.sleep(1)
        self.driver.find_element_by_xpath(PracticeLocators.Quantity).click()
        self.driver.find_element_by_xpath(PracticeLocators.ProductRefilles).click()
        time.sleep(1)
        self.driver.find_element_by_xpath(PracticeLocators.Quantity).click()
        time.sleep(2)
        self.driver.find_element_by_xpath(PracticeLocators.DAWCheckbox).click()
        time.sleep(2)
        instruction = self.driver.find_element_by_xpath(PracticeLocators.productInstruction)
        instruction.click()
        instruction.send_keys(testData.cell(2, 3).value)
        self.driver.find_element_by_xpath(PracticeLocators.allergiesButton).click()
        allergies = self.driver.find_element_by_xpath(PracticeLocators.allergiesTextbox)
        allergies.clear()
        allergies.send_keys(testData.cell(2, 4).value)
        self.driver.find_element_by_xpath(PracticeLocators.doneButton).click()
        self.driver.find_element_by_xpath(PracticeLocators.addDropchartButton).click()
        time.sleep(2)
        element = self.driver.find_element_by_xpath(PracticeLocators.selectDocuments)
        self.driver.execute_script("arguments[0].click()", element)
        self.driver.find_element_by_xpath(PracticeLocators.selectButton).click()
        self.driver.find_element_by_xpath(PracticeLocators.skipPayment).click()
        self.driver.find_element_by_xpath(PracticeLocators.surgeryDate).send_keys(currentDate)
        Notes = self.driver.find_elements(By.XPATH, PracticeLocators.pharmacyNotes)
        if Notes:
            Notes[0].send_keys(testData.cell(2, 5).value)
        else:
            self.driver.find_element_by_xpath(PracticeLocators.addNoteButton).click()
            self.driver.find_element_by_xpath('//textarea[@class="sc-hIVACf cpAwkS"]').send_keys(
                testData.cell(2, 5).value)
            pharmaCheckbox = self.driver.find_elements(By.XPATH, "//label[contains(text(),'Pharmacy')]")
            if pharmaCheckbox:
                pharmaCheckbox[0].click()
            self.driver.find_element_by_xpath(PatientLocators.iframeSaveButton).click()
        createOrderButton = self.driver.find_element_by_xpath(PracticeLocators.submit_CreateOrderButton)
        self.driver.execute_script("arguments[0].click()", createOrderButton)
        time.sleep(7)

    def OnetimeRXProvidePayment(self):
        self.driver.find_element_by_class_name(PracticeLocators.Add_RX).click()
        PatientSearch = self.driver.find_element_by_xpath(PracticeLocators.Patient_search_textbox)
        PatientSearch.click()
        PatientSearch.send_keys(testData.cell(2, 1).value)
        self.driver.find_element_by_xpath("(//*[text()='" + testData.cell(2, 2).value + "'])[1]").click()
        DoctorSearch = self.driver.find_element_by_xpath(PracticeLocators.doctor_search_textbox)
        DoctorSearch.click()
        DoctorSearch.send_keys(scriptData.cell(2, 8).value)
        self.driver.find_element_by_xpath(
            "(//*[text()='" + scriptData.cell(2, 8).value + " " + "Practice'])[2]").click()
        self.driver.find_element_by_xpath(PracticeLocators.NextButton).click()
        self.driver.find_element_by_xpath(PracticeLocators.CreateOnetimeRXButton).click()
        self.driver.find_element_by_name(PracticeLocators.OnetimeSearchMedicine).send_keys(scriptData.cell(2, 1).value)
        time.sleep(2)
        self.driver.find_element_by_xpath("//*[text()='" + scriptData.cell(2, 1).value + "']").click()
        self.driver.find_element_by_xpath(PracticeLocators.AddButton).click()
        self.driver.find_element_by_xpath(PracticeLocators.ProductQuantity).click()
        time.sleep(1)
        self.driver.find_element_by_xpath(PracticeLocators.Quantity).click()
        self.driver.find_element_by_xpath(PracticeLocators.ProductRefilles).click()
        time.sleep(1)
        self.driver.find_element_by_xpath(PracticeLocators.Quantity).click()
        time.sleep(2)
        self.driver.find_element_by_xpath(PracticeLocators.DAWCheckbox).click()
        time.sleep(2)
        instruction = self.driver.find_element_by_xpath(PracticeLocators.productInstruction)
        instruction.click()
        instruction.send_keys(testData.cell(2, 3).value)
        self.driver.find_element_by_xpath(PracticeLocators.allergiesButton).click()
        allergies = self.driver.find_element_by_xpath(PracticeLocators.allergiesTextbox)
        allergies.clear()
        allergies.send_keys(testData.cell(2, 4).value)
        self.driver.find_element_by_xpath(PracticeLocators.doneButton).click()
        self.driver.find_element_by_xpath(PracticeLocators.addDropchartButton).click()
        time.sleep(2)
        element = self.driver.find_element_by_xpath(PracticeLocators.selectDocuments)
        self.driver.execute_script("arguments[0].click()", element)
        self.driver.find_element_by_xpath(PracticeLocators.selectButton).click()
        self.driver.find_element_by_xpath(PracticeLocators.providePayment).click()

        cardName = self.driver.find_element_by_name(PracticeLocators.cardName)
        cardName.clear()
        cardName.send_keys(testData.cell(2, 7).value)

        act = ActionChains(self.driver)
        cardNumber = self.driver.find_element_by_name(PracticeLocators.maskCardNumberField)
        act.move_to_element(cardNumber)
        act.send_keys(PracticeLocators.maskCardNumber)

        cardCVV = self.driver.find_element_by_name(PracticeLocators.cardCVV)
        cardCVV.clear()
        cardCVV.send_keys(testData.cell(2, 9).value)
        Address1 = self.driver.find_element_by_name(PracticeLocators.addressLine1)
        Address1.clear()
        Address1.send_keys(testData.cell(2, 12).value)
        address2 = self.driver.find_element_by_name(PracticeLocators.addressLine2)
        address2.clear()
        address2.send_keys(testData.cell(2, 13).value)
        addressCity = self.driver.find_element_by_name(PracticeLocators.addressCity)
        addressCity.clear()
        addressCity.send_keys(testData.cell(2, 14).value)
        self.driver.find_element_by_xpath(PracticeLocators.addressState).click()
        time.sleep(2)
        self.driver.find_element_by_xpath(PracticeLocators.state).click()
        time.sleep(7)
        addressZipcode = self.driver.find_element_by_name(PracticeLocators.addressZipCode)
        addressZipcode.clear()
        addressZipcode.send_keys(testData.cell(2, 16).value)
        self.driver.find_element_by_xpath(PracticeLocators.continueButton).click()
        self.driver.find_element_by_xpath(PracticeLocators.surgeryDate).send_keys(currentDate)
        Notes = self.driver.find_elements(By.XPATH, PracticeLocators.pharmacyNotes)
        if Notes:
            Notes.send_keys(testData.cell(2, 5).value)
        else:
            self.driver.find_element_by_xpath(PracticeLocators.addNoteButton).click()
            self.driver.find_element_by_xpath('//textarea[@class="sc-hIVACf cpAwkS"]').send_keys(
                testData.cell(2, 5).value)
            pharmaCheckbox = self.driver.find_elements(By.XPATH, "//label[contains(text(),'Pharmacy')]")
            if pharmaCheckbox:
                pharmaCheckbox[0].click()
            self.driver.find_element_by_xpath(PatientLocators.iframeSaveButton).click()
        createOrderButton = self.driver.find_element_by_xpath(PracticeLocators.submit_CreateOrderButton)
        self.driver.execute_script("arguments[0].click()", createOrderButton)
        time.sleep(7)

    def OnetimeOTCProvidePayment(self):
        self.driver.find_element_by_class_name(PracticeLocators.Add_RX).click()
        PatientSearch = self.driver.find_element_by_xpath(PracticeLocators.Patient_search_textbox)
        PatientSearch.click()
        PatientSearch.send_keys(testData.cell(2, 1).value)
        self.driver.find_element_by_xpath("(//*[text()='" + testData.cell(2, 2).value + "'])[1]").click()
        DoctorSearch = self.driver.find_element_by_xpath(PracticeLocators.doctor_search_textbox)
        DoctorSearch.click()
        DoctorSearch.send_keys(scriptData.cell(2, 8).value)
        self.driver.find_element_by_xpath("(//*[text()='" + scriptData.cell(2, 8).value + " " + "Practice'])[2]").click()
        self.driver.find_element_by_xpath(PracticeLocators.NextButton).click()
        self.driver.find_element_by_xpath(PracticeLocators.CreateOnetimeRXButton).click()
        self.driver.find_element_by_name(PracticeLocators.OnetimeSearchMedicine).send_keys(scriptData.cell(2, 2).value)
        time.sleep(2)
        self.driver.find_element_by_xpath("//*[text()='" + scriptData.cell(2, 2).value + "']").click()
        self.driver.find_element_by_xpath(PracticeLocators.AddButton).click()
        self.driver.find_element_by_xpath(PracticeLocators.ProductQuantity).click()
        time.sleep(1)
        self.driver.find_element_by_xpath(PracticeLocators.Quantity).click()
        self.driver.find_element_by_xpath(PracticeLocators.ProductRefilles).click()
        time.sleep(1)
        self.driver.find_element_by_xpath(PracticeLocators.Quantity).click()
        time.sleep(2)
        self.driver.find_element_by_xpath(PracticeLocators.DAWCheckbox).click()
        time.sleep(2)
        instruction = self.driver.find_element_by_xpath(PracticeLocators.productInstruction)
        instruction.click()
        instruction.send_keys(testData.cell(2, 3).value)
        self.driver.find_element_by_xpath(PracticeLocators.allergiesButton).click()
        allergies = self.driver.find_element_by_xpath(PracticeLocators.allergiesTextbox)
        allergies.clear()
        allergies.send_keys(testData.cell(2, 4).value)
        self.driver.find_element_by_xpath(PracticeLocators.doneButton).click()
        self.driver.find_element_by_xpath(PracticeLocators.addDropchartButton).click()
        time.sleep(2)
        element = self.driver.find_element_by_xpath(PracticeLocators.selectDocuments)
        self.driver.execute_script("arguments[0].click()", element)
        self.driver.find_element_by_xpath(PracticeLocators.selectButton).click()
        self.driver.find_element_by_xpath(PracticeLocators.providePayment).click()
        cardname = self.driver.find_element_by_name(PracticeLocators.cardName)
        cardname.clear()
        cardname.send_keys(testData.cell(2, 7).value)
        cardNumber = self.driver.find_element_by_name(PracticeLocators.cardNumber)
        cardNumber.clear()
        cardNumber.send_keys(testData.cell(2, 8).value)
        self.driver.find_element_by_xpath(PracticeLocators.cardMonthDropdown).click()
        time.sleep(1)
        self.driver.find_element_by_xpath(PracticeLocators.cardMonth).click()
        time.sleep(1)
        self.driver.find_element_by_xpath(PracticeLocators.cardYearDropdown).click()
        time.sleep(1)
        self.driver.find_element_by_xpath(PracticeLocators.cardYear).click()
        cardCVV = self.driver.find_element_by_name(PracticeLocators.cardCVV)
        cardCVV.clear()
        cardCVV.send_keys(testData.cell(2, 9).value)
        Address1 = self.driver.find_element_by_name(PracticeLocators.addressLine1)
        Address1.clear()
        Address1.send_keys(testData.cell(2, 12).value)
        address2 = self.driver.find_element_by_name(PracticeLocators.addressLine2)
        address2.clear()
        address2.send_keys(testData.cell(2, 13).value)
        addressCity = self.driver.find_element_by_name(PracticeLocators.addressCity)
        addressCity.clear()
        addressCity.send_keys(testData.cell(2, 14).value)
        self.driver.find_element_by_xpath(PracticeLocators.addressState).click()
        time.sleep(2)
        self.driver.find_element_by_xpath(PracticeLocators.state).click()
        addressZipcode = self.driver.find_element_by_name(PracticeLocators.addressZipCode)
        addressZipcode.clear()
        addressZipcode.send_keys(testData.cell(2, 16).value)
        self.driver.find_element_by_xpath(PracticeLocators.continueButton).click()
        self.driver.find_element_by_xpath(PracticeLocators.surgeryDate).send_keys(currentDate)
        Notes = self.driver.find_elements(By.XPATH, PracticeLocators.pharmacyNotes)
        if Notes:
            Notes.send_keys(testData.cell(2, 5).value)
        else:
            self.driver.find_element_by_xpath(PracticeLocators.addNoteButton).click()
            self.driver.find_element_by_xpath('//textarea[@class="sc-hIVACf cpAwkS"]').send_keys(
                testData.cell(2, 5).value)
            pharmaCheckbox = self.driver.find_elements(By.XPATH, "//label[contains(text(),'Pharmacy')]")
            if pharmaCheckbox:
                pharmaCheckbox[0].click()
            self.driver.find_element_by_xpath(PatientLocators.iframeSaveButton).click()
        createOrderButton = self.driver.find_element_by_xpath(PracticeLocators.submit_CreateOrderButton)
        self.driver.execute_script("arguments[0].click()", createOrderButton)
        time.sleep(7)

    def OnetimeCompoundProvidePayment(self):
        self.driver.find_element_by_class_name(PracticeLocators.Add_RX).click()
        PatientSearch = self.driver.find_element_by_xpath(PracticeLocators.Patient_search_textbox)
        PatientSearch.click()
        PatientSearch.send_keys(testData.cell(2, 1).value)
        self.driver.find_element_by_xpath("(//*[text()='" + testData.cell(2, 2).value + "'])[1]").click()
        DoctorSearch = self.driver.find_element_by_xpath(PracticeLocators.doctor_search_textbox)
        DoctorSearch.click()
        DoctorSearch.send_keys(scriptData.cell(2, 8).value)
        self.driver.find_element_by_xpath("(//*[text()='" + scriptData.cell(2, 8).value + " " + "Practice'])[2]").click()
        self.driver.find_element_by_xpath(PracticeLocators.NextButton).click()
        self.driver.find_element_by_xpath(PracticeLocators.CreateOnetimeRXButton).click()
        self.driver.find_element_by_name(PracticeLocators.OnetimeSearchMedicine).send_keys(scriptData.cell(2, 3).value)
        time.sleep(2)
        self.driver.find_element_by_xpath("//*[text()='" + scriptData.cell(2, 3).value + "']").click()
        self.driver.find_element_by_xpath(PracticeLocators.AddButton).click()
        self.driver.find_element_by_xpath(PracticeLocators.ProductQuantity).click()
        time.sleep(1)
        self.driver.find_element_by_xpath(PracticeLocators.Quantity).click()
        self.driver.find_element_by_xpath(PracticeLocators.ProductRefilles).click()
        time.sleep(1)
        self.driver.find_element_by_xpath(PracticeLocators.Quantity).click()
        time.sleep(2)
        self.driver.find_element_by_xpath(PracticeLocators.DAWCheckbox).click()
        time.sleep(2)
        instruction = self.driver.find_element_by_xpath(PracticeLocators.productInstruction)
        instruction.click()
        instruction.send_keys(testData.cell(2, 3).value)
        self.driver.find_element_by_xpath(PracticeLocators.allergiesButton).click()
        allergies = self.driver.find_element_by_xpath(PracticeLocators.allergiesTextbox)
        allergies.clear()
        allergies.send_keys(testData.cell(2, 4).value)
        self.driver.find_element_by_xpath(PracticeLocators.doneButton).click()
        self.driver.find_element_by_xpath(PracticeLocators.addDropchartButton).click()
        time.sleep(2)
        element = self.driver.find_element_by_xpath(PracticeLocators.selectDocuments)
        self.driver.execute_script("arguments[0].click()", element)
        self.driver.find_element_by_xpath(PracticeLocators.selectButton).click()
        self.driver.find_element_by_xpath(PracticeLocators.providePayment).click()
        cardname = self.driver.find_element_by_name(PracticeLocators.cardName)
        cardname.clear()
        cardname.send_keys(testData.cell(2, 7).value)
        cardNumber = self.driver.find_element_by_name(PracticeLocators.cardNumber)
        cardNumber.clear()
        cardNumber.send_keys(testData.cell(2, 8).value)
        self.driver.find_element_by_xpath(PracticeLocators.cardMonthDropdown).click()
        time.sleep(1)
        self.driver.find_element_by_xpath(PracticeLocators.cardMonth).click()
        time.sleep(1)
        self.driver.find_element_by_xpath(PracticeLocators.cardYearDropdown).click()
        time.sleep(1)
        self.driver.find_element_by_xpath(PracticeLocators.cardYear).click()
        cardCVV = self.driver.find_element_by_name(PracticeLocators.cardCVV)
        cardCVV.clear()
        cardCVV.send_keys(testData.cell(2, 9).value)
        Address1 = self.driver.find_element_by_name(PracticeLocators.addressLine1)
        Address1.clear()
        Address1.send_keys(testData.cell(2, 12).value)
        address2 = self.driver.find_element_by_name(PracticeLocators.addressLine2)
        address2.clear()
        address2.send_keys(testData.cell(2, 13).value)
        addressCity = self.driver.find_element_by_name(PracticeLocators.addressCity)
        addressCity.clear()
        addressCity.send_keys(testData.cell(2, 14).value)
        self.driver.find_element_by_xpath(PracticeLocators.addressState).click()
        time.sleep(2)
        self.driver.find_element_by_xpath(PracticeLocators.state).click()
        addressZipcode = self.driver.find_element_by_name(PracticeLocators.addressZipCode)
        addressZipcode.clear()
        addressZipcode.send_keys(testData.cell(2, 16).value)
        self.driver.find_element_by_xpath(PracticeLocators.continueButton).click()
        self.driver.find_element_by_xpath(PracticeLocators.surgeryDate).send_keys(currentDate)
        Notes = self.driver.find_elements(By.XPATH, PracticeLocators.pharmacyNotes)
        if Notes:
            Notes.send_keys(testData.cell(2, 5).value)
        else:
            self.driver.find_element_by_xpath(PracticeLocators.addNoteButton).click()
            self.driver.find_element_by_xpath('//textarea[@class="sc-hIVACf cpAwkS"]').send_keys(
                testData.cell(2, 5).value)
            pharmaCheckbox = self.driver.find_elements(By.XPATH, "//label[contains(text(),'Pharmacy')]")
            if pharmaCheckbox:
                pharmaCheckbox[0].click()
            self.driver.find_element_by_xpath(PatientLocators.iframeSaveButton).click()
        createOrderButton = self.driver.find_element_by_xpath(PracticeLocators.submit_CreateOrderButton)
        self.driver.execute_script("arguments[0].click()", createOrderButton)
        time.sleep(7)

    def SubscriptionRXProvidePayment(self):
        self.driver.find_element_by_class_name(PracticeLocators.Add_RX).click()
        PatientSearch = self.driver.find_element_by_xpath(PracticeLocators.Patient_search_textbox)
        PatientSearch.click()
        PatientSearch.send_keys(testData.cell(2, 1).value)
        self.driver.find_element_by_xpath("(//*[text()='" + testData.cell(2, 2).value + "'])[1]").click()
        DoctorSearch = self.driver.find_element_by_xpath(PracticeLocators.doctor_search_textbox)
        DoctorSearch.click()
        DoctorSearch.send_keys(scriptData.cell(2, 8).value)
        self.driver.find_element_by_xpath("(//*[text()='" + scriptData.cell(2, 8).value + " " + "Practice'])[2]").click()
        self.driver.find_element_by_xpath(PracticeLocators.NextButton).click()
        time.sleep(2)
        el = self.driver.find_element_by_xpath(PracticeLocators.createSubscriptionRxButton)
        self.driver.execute_script('arguments[0].click()', el)
        self.driver.find_element_by_xpath(PracticeLocators.subscriptionProductSearch).send_keys(scriptData.cell(2, 1).value)
        time.sleep(2)
        self.driver.find_element_by_xpath("//*[text()='" + scriptData.cell(2, 1).value + "']").click()
        self.driver.find_element_by_xpath(PracticeLocators.AddButton).click()
        self.driver.find_element_by_xpath(PracticeLocators.ProductQuantity).click()
        time.sleep(1)
        self.driver.find_element_by_xpath(PracticeLocators.Quantity).click()
        self.driver.find_element_by_xpath(PracticeLocators.ProductRefilles).click()
        time.sleep(1)
        self.driver.find_element_by_xpath(PracticeLocators.Quantity).click()
        time.sleep(2)
        self.driver.find_element_by_xpath(PracticeLocators.DAWCheckbox).click()
        time.sleep(2)
        instruction = self.driver.find_element_by_xpath(PracticeLocators.productInstruction)
        instruction.click()
        instruction.send_keys(testData.cell(2, 3).value)
        self.driver.find_element_by_xpath(PracticeLocators.allergiesButton).click()
        allergies = self.driver.find_element_by_xpath(PracticeLocators.allergiesTextbox)
        allergies.clear()
        allergies.send_keys(testData.cell(2, 4).value)
        self.driver.find_element_by_xpath(PracticeLocators.doneButton).click()
        self.driver.find_element_by_xpath(PracticeLocators.addDropchartButton).click()
        time.sleep(2)
        element = self.driver.find_element_by_xpath(PracticeLocators.selectDocuments)
        self.driver.execute_script("arguments[0].click()", element)
        self.driver.find_element_by_xpath(PracticeLocators.selectButton).click()
        self.driver.find_element_by_xpath(PracticeLocators.providePayment).click()
        cardname = self.driver.find_element_by_name(PracticeLocators.cardName)
        cardname.clear()
        cardname.send_keys(testData.cell(2, 7).value)
        cardNumber = self.driver.find_element_by_name(PracticeLocators.cardNumber)
        cardNumber.clear()
        cardNumber.send_keys(testData.cell(2, 8).value)
        self.driver.find_element_by_xpath(PracticeLocators.cardMonthDropdown).click()
        time.sleep(1)
        self.driver.find_element_by_xpath(PracticeLocators.cardMonth).click()
        time.sleep(1)
        self.driver.find_element_by_xpath(PracticeLocators.cardYearDropdown).click()
        time.sleep(1)
        self.driver.find_element_by_xpath(PracticeLocators.cardYear).click()
        cardCVV = self.driver.find_element_by_name(PracticeLocators.cardCVV)
        cardCVV.clear()
        cardCVV.send_keys(testData.cell(2, 9).value)
        Address1 = self.driver.find_element_by_name(PracticeLocators.addressLine1)
        Address1.clear()
        Address1.send_keys(testData.cell(2, 12).value)
        address2 = self.driver.find_element_by_name(PracticeLocators.addressLine2)
        address2.clear()
        address2.send_keys(testData.cell(2, 13).value)
        addressCity = self.driver.find_element_by_name(PracticeLocators.addressCity)
        addressCity.clear()
        addressCity.send_keys(testData.cell(2, 14).value)
        self.driver.find_element_by_xpath(PracticeLocators.addressState).click()
        time.sleep(2)
        self.driver.find_element_by_xpath(PracticeLocators.state).click()
        addressZipcode = self.driver.find_element_by_name(PracticeLocators.addressZipCode)
        addressZipcode.clear()
        addressZipcode.send_keys(testData.cell(2, 16).value)
        self.driver.find_element_by_xpath(PracticeLocators.continueButton).click()
        self.driver.find_element_by_xpath(PracticeLocators.surgeryDate).send_keys(currentDate)
        Notes = self.driver.find_elements(By.XPATH, PracticeLocators.pharmacyNotes)
        if Notes:
            Notes.send_keys(testData.cell(2, 5).value)
        else:
            self.driver.find_element_by_xpath(PracticeLocators.addNoteButton).click()
            self.driver.find_element_by_xpath('//textarea[@class="sc-hIVACf cpAwkS"]').send_keys(
                testData.cell(2, 5).value)
            pharmaCheckbox = self.driver.find_elements(By.XPATH, "//label[contains(text(),'Pharmacy')]")
            if pharmaCheckbox:
                pharmaCheckbox[0].click()
            self.driver.find_element_by_xpath(PatientLocators.iframeSaveButton).click()
        createOrderButton = self.driver.find_element_by_xpath(PracticeLocators.submit_CreateOrderButton)
        self.driver.execute_script("arguments[0].click()", createOrderButton)
        time.sleep(7)

    def SubscriptionOTCProvidePayment(self):
        self.driver.find_element_by_class_name(PracticeLocators.Add_RX).click()
        PatientSearch = self.driver.find_element_by_xpath(PracticeLocators.Patient_search_textbox)
        PatientSearch.click()
        PatientSearch.send_keys(testData.cell(2, 1).value)
        self.driver.find_element_by_xpath("(//*[text()='" + testData.cell(2, 2).value + "'])[1]").click()
        DoctorSearch = self.driver.find_element_by_xpath(PracticeLocators.doctor_search_textbox)
        DoctorSearch.click()
        DoctorSearch.send_keys(scriptData.cell(2, 8).value)
        self.driver.find_element_by_xpath("(//*[text()='" + scriptData.cell(2, 8).value + " " + "Practice'])[2]").click()
        self.driver.find_element_by_xpath(PracticeLocators.NextButton).click()
        time.sleep(2)
        el = self.driver.find_element_by_xpath(PracticeLocators.createSubscriptionRxButton)
        self.driver.execute_script('arguments[0].click()', el)
        self.driver.find_element_by_xpath(PracticeLocators.subscriptionProductSearch).send_keys(scriptData.cell(2, 2).value)
        time.sleep(2)
        self.driver.find_element_by_xpath("//*[text()='" + scriptData.cell(2, 2).value + "']").click()
        self.driver.find_element_by_xpath(PracticeLocators.AddButton).click()
        self.driver.find_element_by_xpath(PracticeLocators.ProductQuantity).click()
        time.sleep(1)
        self.driver.find_element_by_xpath(PracticeLocators.Quantity).click()
        self.driver.find_element_by_xpath(PracticeLocators.ProductRefilles).click()
        time.sleep(1)
        self.driver.find_element_by_xpath(PracticeLocators.Quantity).click()
        time.sleep(2)
        self.driver.find_element_by_xpath(PracticeLocators.DAWCheckbox).click()
        time.sleep(2)
        instruction = self.driver.find_element_by_xpath(PracticeLocators.productInstruction)
        instruction.click()
        instruction.send_keys(testData.cell(2, 3).value)
        self.driver.find_element_by_xpath(PracticeLocators.allergiesButton).click()
        allergies = self.driver.find_element_by_xpath(PracticeLocators.allergiesTextbox)
        allergies.clear()
        allergies.send_keys(testData.cell(2, 4).value)
        self.driver.find_element_by_xpath(PracticeLocators.doneButton).click()
        self.driver.find_element_by_xpath(PracticeLocators.addDropchartButton).click()
        time.sleep(2)
        element = self.driver.find_element_by_xpath(PracticeLocators.selectDocuments)
        self.driver.execute_script("arguments[0].click()", element)
        self.driver.find_element_by_xpath(PracticeLocators.selectButton).click()
        self.driver.find_element_by_xpath(PracticeLocators.providePayment).click()
        cardname = self.driver.find_element_by_name(PracticeLocators.cardName)
        cardname.clear()
        cardname.send_keys(testData.cell(2, 7).value)
        cardNumber = self.driver.find_element_by_name(PracticeLocators.cardNumber)
        cardNumber.clear()
        cardNumber.send_keys(testData.cell(2, 8).value)
        self.driver.find_element_by_xpath(PracticeLocators.cardMonthDropdown).click()
        time.sleep(1)
        self.driver.find_element_by_xpath(PracticeLocators.cardMonth).click()
        time.sleep(1)
        self.driver.find_element_by_xpath(PracticeLocators.cardYearDropdown).click()
        time.sleep(1)
        self.driver.find_element_by_xpath(PracticeLocators.cardYear).click()
        cardCVV = self.driver.find_element_by_name(PracticeLocators.cardCVV)
        cardCVV.clear()
        cardCVV.send_keys(testData.cell(2, 9).value)
        Address1 = self.driver.find_element_by_name(PracticeLocators.addressLine1)
        Address1.clear()
        Address1.send_keys(testData.cell(2, 12).value)
        address2 = self.driver.find_element_by_name(PracticeLocators.addressLine2)
        address2.clear()
        address2.send_keys(testData.cell(2, 13).value)
        addressCity = self.driver.find_element_by_name(PracticeLocators.addressCity)
        addressCity.clear()
        addressCity.send_keys(testData.cell(2, 14).value)
        self.driver.find_element_by_xpath(PracticeLocators.addressState).click()
        time.sleep(2)
        self.driver.find_element_by_xpath(PracticeLocators.state).click()
        addressZipcode = self.driver.find_element_by_name(PracticeLocators.addressZipCode)
        addressZipcode.clear()
        addressZipcode.send_keys(testData.cell(2, 16).value)
        self.driver.find_element_by_xpath(PracticeLocators.continueButton).click()
        self.driver.find_element_by_xpath(PracticeLocators.surgeryDate).send_keys(currentDate)
        Notes = self.driver.find_elements(By.XPATH, PracticeLocators.pharmacyNotes)
        if Notes:
            Notes.send_keys(testData.cell(2, 5).value)
        else:
            self.driver.find_element_by_xpath(PracticeLocators.addNoteButton).click()
            self.driver.find_element_by_xpath('//textarea[@class="sc-hIVACf cpAwkS"]').send_keys(
                testData.cell(2, 5).value)
            pharmaCheckbox = self.driver.find_elements(By.XPATH, "//label[contains(text(),'Pharmacy')]")
            if pharmaCheckbox:
                pharmaCheckbox[0].click()
            self.driver.find_element_by_xpath(PatientLocators.iframeSaveButton).click()
        createOrderButton = self.driver.find_element_by_xpath(PracticeLocators.submit_CreateOrderButton)
        self.driver.execute_script("arguments[0].click()", createOrderButton)
        time.sleep(7)

    def SubscriptionCompoundProvidePayment(self):
        self.driver.find_element_by_class_name(PracticeLocators.Add_RX).click()
        PatientSearch = self.driver.find_element_by_xpath(PracticeLocators.Patient_search_textbox)
        PatientSearch.click()
        PatientSearch.send_keys(testData.cell(2, 1).value)
        self.driver.find_element_by_xpath("(//*[text()='" + testData.cell(2, 2).value + "'])[1]").click()
        DoctorSearch = self.driver.find_element_by_xpath(PracticeLocators.doctor_search_textbox)
        DoctorSearch.click()
        DoctorSearch.send_keys(scriptData.cell(2, 8).value)
        self.driver.find_element_by_xpath("(//*[text()='" + scriptData.cell(2, 8).value + " " + "Practice'])[2]").click()
        self.driver.find_element_by_xpath(PracticeLocators.NextButton).click()
        time.sleep(2)
        el = self.driver.find_element_by_xpath(PracticeLocators.createSubscriptionRxButton)
        self.driver.execute_script('arguments[0].click()', el)
        self.driver.find_element_by_xpath(PracticeLocators.subscriptionProductSearch).send_keys(scriptData.cell(2, 3).value)
        time.sleep(2)
        self.driver.find_element_by_xpath("//*[text()='" + scriptData.cell(2, 3).value + "']").click()
        self.driver.find_element_by_xpath(PracticeLocators.AddButton).click()
        self.driver.find_element_by_xpath(PracticeLocators.ProductQuantity).click()
        time.sleep(1)
        self.driver.find_element_by_xpath(PracticeLocators.Quantity).click()
        self.driver.find_element_by_xpath(PracticeLocators.ProductRefilles).click()
        time.sleep(1)
        self.driver.find_element_by_xpath(PracticeLocators.Quantity).click()
        time.sleep(2)
        self.driver.find_element_by_xpath(PracticeLocators.DAWCheckbox).click()
        time.sleep(2)
        instruction = self.driver.find_element_by_xpath(PracticeLocators.productInstruction)
        instruction.click()
        instruction.send_keys(testData.cell(2, 3).value)
        self.driver.find_element_by_xpath(PracticeLocators.allergiesButton).click()
        allergies = self.driver.find_element_by_xpath(PracticeLocators.allergiesTextbox)
        allergies.clear()
        allergies.send_keys(testData.cell(2, 4).value)
        self.driver.find_element_by_xpath(PracticeLocators.doneButton).click()
        self.driver.find_element_by_xpath(PracticeLocators.addDropchartButton).click()
        time.sleep(2)
        element = self.driver.find_element_by_xpath(PracticeLocators.selectDocuments)
        self.driver.execute_script("arguments[0].click()", element)
        self.driver.find_element_by_xpath(PracticeLocators.selectButton).click()
        self.driver.find_element_by_xpath(PracticeLocators.providePayment).click()
        cardname = self.driver.find_element_by_name(PracticeLocators.cardName)
        cardname.clear()
        cardname.send_keys(testData.cell(2, 7).value)
        cardNumber = self.driver.find_element_by_name(PracticeLocators.cardNumber)
        cardNumber.clear()
        cardNumber.send_keys(testData.cell(2, 8).value)
        self.driver.find_element_by_xpath(PracticeLocators.cardMonthDropdown).click()
        time.sleep(1)
        self.driver.find_element_by_xpath(PracticeLocators.cardMonth).click()
        time.sleep(1)
        self.driver.find_element_by_xpath(PracticeLocators.cardYearDropdown).click()
        time.sleep(1)
        self.driver.find_element_by_xpath(PracticeLocators.cardYear).click()
        cardCVV = self.driver.find_element_by_name(PracticeLocators.cardCVV)
        cardCVV.clear()
        cardCVV.send_keys(testData.cell(2, 9).value)
        Address1 = self.driver.find_element_by_name(PracticeLocators.addressLine1)
        Address1.clear()
        Address1.send_keys(testData.cell(2, 12).value)
        address2 = self.driver.find_element_by_name(PracticeLocators.addressLine2)
        address2.clear()
        address2.send_keys(testData.cell(2, 13).value)
        addressCity = self.driver.find_element_by_name(PracticeLocators.addressCity)
        addressCity.clear()
        addressCity.send_keys(testData.cell(2, 14).value)
        self.driver.find_element_by_xpath(PracticeLocators.addressState).click()
        time.sleep(2)
        self.driver.find_element_by_xpath(PracticeLocators.state).click()
        addressZipcode = self.driver.find_element_by_name(PracticeLocators.addressZipCode)
        addressZipcode.clear()
        addressZipcode.send_keys(testData.cell(2, 16).value)
        self.driver.find_element_by_xpath(PracticeLocators.continueButton).click()
        self.driver.find_element_by_xpath(PracticeLocators.surgeryDate).send_keys(currentDate)
        Notes = self.driver.find_elements(By.XPATH, PracticeLocators.pharmacyNotes)
        if Notes:
            Notes.send_keys(testData.cell(2, 5).value)
        else:
            self.driver.find_element_by_xpath(PracticeLocators.addNoteButton).click()
            self.driver.find_element_by_xpath('//textarea[@class="sc-hIVACf cpAwkS"]').send_keys(
                testData.cell(2, 5).value)
            pharmaCheckbox = self.driver.find_elements(By.XPATH, "//label[contains(text(),'Pharmacy')]")
            if pharmaCheckbox:
                pharmaCheckbox[0].click()
            self.driver.find_element_by_xpath(PatientLocators.iframeSaveButton).click()
        createOrderButton = self.driver.find_element_by_xpath(PracticeLocators.submit_CreateOrderButton)
        self.driver.execute_script("arguments[0].click()", createOrderButton)
        time.sleep(7)

    def EditOrder(self):
        self.driver.find_element_by_link_text('Orders').click()
        self.driver.find_element_by_xpath('//*[@class="table"]//*[a]').click()
        self.driver.find_element_by_link_text('Edit Contents').click()
        self.driver.find_element_by_xpath('//*[@class="sc-hXRMBi eQtMFe"]').click()
        self.driver.find_element_by_xpath(PracticeLocators.searchForMedication).click()
        time.sleep(3)
        self.driver.find_element_by_xpath("//*[text()='150 Rx']").click()
        self.driver.find_element_by_xpath(PracticeLocators.AddButton).click()
        time.sleep(1)
        self.driver.find_element_by_xpath(PracticeLocators.skipPayment).click()
        self.driver.find_element_by_xpath(PracticeLocators.updateOrderButton).click()
        time.sleep(7)
        if "You're all set!" in self.driver.page_source:
            self.driver.find_element_by_partial_link_text("Return to Dashboard").click()
        else:
            print("\nOrder not created")

        self.driver.find_element_by_class_name('account-link-label').click()
        self.driver.find_element_by_link_text('Sign Out').click()
        assert self.driver.current_url == loginData.cell(2, 2).value
        time.sleep(1)
        self.driver.close()
