import time
from faker import Faker
from datetime import date
from openpyxl import load_workbook
from selenium.webdriver import Keys
from Locators.Locators import Locators
from selenium.webdriver import ActionChains
from selenium.webdriver.common.by import By
from Locators.PatientLocators import PatientLocators
from Locators.PracticeLocators import PracticeLocators
from Locators.DispenserLocators import DispenserLocators

FilePath = "C:/Users/Administrator/PycharmProject/LegrandePython/TestData/Data.xlsx"
datafile = load_workbook(FilePath)
testData = datafile['Test Data']
loginData = datafile["Login Credentials"]
scriptData = datafile["Script Data"]

faker = Faker()
today = date.today()
currentDate = today.strftime("%m/%d/%Y")
FirstName = faker.first_name()
LastName = faker.last_name()
PhoneNumber = faker.phone_number()
EmailAddress = FirstName + "." + LastName + "@mailinator.com"


class CommanFlow:
    def __init__(self, driver):
        self.driver = driver

    def CreatePatient(self):
        self.driver.find_element_by_class_name(PracticeLocators.addPersonButton).click()
        self.driver.find_element_by_name(PracticeLocators.firstName).send_keys(FirstName)
        self.driver.find_element_by_name(PracticeLocators.lastName).send_keys(LastName)
        self.driver.find_element_by_name(PracticeLocators.birthDate).send_keys(currentDate)
        self.driver.find_element_by_name(PracticeLocators.phoneNumber).send_keys(PhoneNumber)
        self.driver.find_element_by_name(Locators.Email).send_keys(EmailAddress.lower())
        self.driver.find_element_by_xpath(PracticeLocators.createAccountButton).click()
        time.sleep(5)
        if "Congratulations, you have successfully created a new Patient Account." in self.driver.page_source:
            self.driver.find_element_by_xpath(PracticeLocators.closeButton).click()
            testData.cell(2, 1).value = FirstName + " " + LastName
            testData.cell(2, 2).value = FirstName + " " + LastName + " (" + currentDate + ")"
            loginData.cell(8, 3).value = EmailAddress.lower()
            datafile.save(FilePath)
            print("\nPatient Created Successfully")
        else:
            print("\nPatient not Created")
        self.driver.close()

    def CreateUser(self):
        self.driver.find_element_by_class_name(PracticeLocators.accountLinkLabel).click()
        self.driver.find_element_by_link_text(PracticeLocators.manageUser).click()
        self.driver.find_element_by_xpath(PracticeLocators.addUserButton).click()
        self.driver.find_element_by_name(PracticeLocators.firstName).send_keys(FirstName)
        self.driver.find_element_by_name(PracticeLocators.lastName).send_keys(LastName)
        self.driver.find_element_by_name(Locators.Email).send_keys(EmailAddress.lower())
        self.driver.find_element_by_name(PracticeLocators.phoneNumber).send_keys(PhoneNumber)
        self.driver.find_element_by_class_name(PracticeLocators.selectAccountType).click()
        time.sleep(2)
        self.driver.find_element_by_xpath(PracticeLocators.clerkOption).click()
        time.sleep(1)
        self.driver.find_element_by_xpath(PracticeLocators.createAccountButton).click()
        time.sleep(3)
        if "Congratulations. You have successfully created new user profile." in self.driver.page_source:
            self.driver.find_element_by_xpath(PracticeLocators.dismissButton).click()
            print("\nUser created successfully")
        else:
            print("\nUser not created")
        self.driver.close()

    def PatientMainSearch(self):
        self.driver.find_element_by_class_name(PracticeLocators.mainPatientSearch).click()
        self.driver.find_element_by_xpath(PracticeLocators.mainSearchTextbox).send_keys(testData.cell(2, 1).value)
        self.driver.find_element_by_class_name(PracticeLocators.mainSearchButton).click()
        try:
            self.driver.find_element_by_xpath(PracticeLocators.tableRow).click()
            try:
                self.driver.find_element_by_link_text(PracticeLocators.viewDetails).click()
            except:
                print("\nOrder not created for " + testData.cell(2, 1).value + ".")
        except:
            print("\nPatient: " + testData.cell(2, 1).value + " not found...")
        self.driver.close()

    def ChangeProductPrice(self):
        self.driver.find_element_by_class_name(PracticeLocators.accountLinkLabel).click()
        self.driver.find_element_by_link_text(DispenserLocators.productList).click()
        time.sleep(2)
        self.driver.find_element_by_xpath(PracticeLocators.tableRow).click()
        self.driver.find_element_by_xpath(DispenserLocators.updateButton).click()
        self.driver.find_element_by_xpath(DispenserLocators.changePriceButton).click()
        if "You have successfully updated the price of 100 Compound" in self.driver.page_source:
            self.driver.find_element_by_xpath(PracticeLocators.closeButton).click()
            print('\nProduct price changed successfully')
        else:
            print('\nProduct price not changed')
        self.driver.close()

    def OnetimeRXSkipPayment(self):
        self.driver.implicitly_wait(20)
        self.driver.find_element_by_class_name(PracticeLocators.Add_RX).click()
        PatientSearch = self.driver.find_element_by_xpath(PracticeLocators.Patient_search_textbox)
        PatientSearch.click()
        PatientSearch.send_keys(testData.cell(2, 1).value)
        self.driver.find_element_by_xpath("(//*[text()='" + testData.cell(2, 2).value + "'])[1]").click()
        DoctorSearch = self.driver.find_element_by_xpath(PracticeLocators.doctor_search_textbox)
        DoctorSearch.click()
        DoctorSearch.send_keys(scriptData.cell(2, 8).value)
        self.driver.find_element_by_xpath(
            "(//*[text()='" + scriptData.cell(2, 8).value + " " + "Practice'])[2]").click()
        self.driver.find_element_by_xpath(PracticeLocators.NextButton).click()
        self.driver.find_element_by_xpath(PracticeLocators.CreateOnetimeRXButton).click()
        self.driver.find_element_by_name(PracticeLocators.OnetimeSearchMedicine).send_keys(scriptData.cell(2, 1).value)
        time.sleep(2)
        self.driver.find_element_by_xpath("//*[text()='" + scriptData.cell(2, 1).value + "']").click()
        self.driver.find_element_by_xpath(PracticeLocators.AddButton).click()
        self.driver.find_element_by_xpath(PracticeLocators.ProductQuantity).click()
        time.sleep(1)
        self.driver.find_element_by_xpath(PracticeLocators.Quantity).click()
        self.driver.find_element_by_xpath(PracticeLocators.ProductRefilles).click()
        time.sleep(1)
        self.driver.find_element_by_xpath(PracticeLocators.Quantity).click()
        time.sleep(2)
        self.driver.find_element_by_xpath(PracticeLocators.DAWCheckbox).click()
        time.sleep(2)
        instruction = self.driver.find_element_by_xpath(PracticeLocators.productInstruction)
        instruction.click()
        instruction.send_keys(testData.cell(2, 3).value)
        self.driver.find_element_by_xpath(PracticeLocators.allergiesButton).click()
        allergies = self.driver.find_element_by_xpath(PracticeLocators.allergiesTextbox)
        allergies.clear()
        allergies.send_keys(testData.cell(2, 4).value)
        self.driver.find_element_by_xpath(PracticeLocators.doneButton).click()
        self.driver.find_element_by_xpath(PracticeLocators.addDropchartButton).click()
        time.sleep(2)
        element = self.driver.find_element_by_xpath(PracticeLocators.selectDocuments)
        self.driver.execute_script("arguments[0].click()", element)
        self.driver.find_element_by_xpath(PracticeLocators.selectButton).click()
        self.driver.find_element_by_xpath(PracticeLocators.skipPayment).click()
        self.driver.find_element_by_xpath(PracticeLocators.surgeryDate).send_keys(currentDate)
        Notes = self.driver.find_elements(By.XPATH, PracticeLocators.pharmacyNotes)
        if Notes:
            Notes[0].send_keys(testData.cell(2, 5).value)
        else:
            self.driver.find_element_by_xpath(DispenserLocators.addNoteButton).click()
            self.driver.find_element_by_xpath('//textarea[@class="sc-hIVACf cpAwkS"]').send_keys(testData.cell(2, 5).value)
            pharmaCheckbox = self.driver.find_elements(By.XPATH, "//label[contains(text(),'Pharmacy')]")
            if pharmaCheckbox:
                pharmaCheckbox[0].click()
            self.driver.find_element_by_xpath(PatientLocators.iframeSaveButton).click()
        createOrderButton = self.driver.find_element_by_xpath(PracticeLocators.submit_CreateOrderButton)
        self.driver.execute_script("arguments[0].click()", createOrderButton)
        time.sleep(7)

    def OnetimeOTCSkipPayment(self):
        self.driver.find_element_by_class_name(PracticeLocators.Add_RX).click()
        PatientSearch = self.driver.find_element_by_xpath(PracticeLocators.Patient_search_textbox)
        PatientSearch.click()
        PatientSearch.send_keys(testData.cell(2, 1).value)
        self.driver.find_element_by_xpath("(//*[text()='" + testData.cell(2, 2).value + "'])[1]").click()
        DoctorSearch = self.driver.find_element_by_xpath(PracticeLocators.doctor_search_textbox)
        DoctorSearch.click()
        DoctorSearch.send_keys(scriptData.cell(2, 8).value)
        self.driver.find_element_by_xpath(
            "(//*[text()='" + scriptData.cell(2, 8).value + " " + "Practice'])[2]").click()
        self.driver.find_element_by_xpath(PracticeLocators.NextButton).click()
        self.driver.find_element_by_xpath(PracticeLocators.CreateOnetimeRXButton).click()
        self.driver.find_element_by_name(PracticeLocators.OnetimeSearchMedicine).send_keys(scriptData.cell(2, 2).value)
        time.sleep(2)
        self.driver.find_element_by_xpath("//*[text()='" + scriptData.cell(2, 2).value + "']").click()
        self.driver.find_element_by_xpath(PracticeLocators.AddButton).click()
        self.driver.find_element_by_xpath(PracticeLocators.ProductQuantity).click()
        time.sleep(1)
        self.driver.find_element_by_xpath(PracticeLocators.Quantity).click()
        self.driver.find_element_by_xpath(PracticeLocators.ProductRefilles).click()
        time.sleep(1)
        self.driver.find_element_by_xpath(PracticeLocators.Quantity).click()
        time.sleep(2)
        self.driver.find_element_by_xpath(PracticeLocators.DAWCheckbox).click()
        time.sleep(2)
        instruction = self.driver.find_element_by_xpath(PracticeLocators.productInstruction)
        instruction.click()
        instruction.send_keys(testData.cell(2, 3).value)
        self.driver.find_element_by_xpath(PracticeLocators.allergiesButton).click()
        allergies = self.driver.find_element_by_xpath(PracticeLocators.allergiesTextbox)
        allergies.clear()
        allergies.send_keys(testData.cell(2, 4).value)
        self.driver.find_element_by_xpath(PracticeLocators.doneButton).click()
        self.driver.find_element_by_xpath(PracticeLocators.addDropchartButton).click()
        time.sleep(2)
        element = self.driver.find_element_by_xpath(PracticeLocators.selectDocuments)
        self.driver.execute_script("arguments[0].click()", element)
        self.driver.find_element_by_xpath(PracticeLocators.selectButton).click()
        self.driver.find_element_by_xpath(PracticeLocators.skipPayment).click()
        self.driver.find_element_by_xpath(PracticeLocators.surgeryDate).send_keys(currentDate)
        Notes = self.driver.find_elements(By.XPATH, PracticeLocators.pharmacyNotes)
        if Notes:
            Notes[0].send_keys(testData.cell(2, 5).value)
        else:
            self.driver.find_element_by_xpath(DispenserLocators.addNoteButton).click()
            self.driver.find_element_by_xpath('//textarea[@class="sc-hIVACf cpAwkS"]').send_keys(
                testData.cell(2, 5).value)
            pharmaCheckbox = self.driver.find_elements(By.XPATH, "//label[contains(text(),'Pharmacy')]")
            if pharmaCheckbox:
                pharmaCheckbox[0].click()
            self.driver.find_element_by_xpath(PatientLocators.iframeSaveButton).click()
        createOrderButton = self.driver.find_element_by_xpath(PracticeLocators.submit_CreateOrderButton)
        self.driver.execute_script("arguments[0].click()", createOrderButton)
        time.sleep(7)

    def OnetimeCompoundSkipPayment(self):
        self.driver.find_element_by_class_name(PracticeLocators.Add_RX).click()
        PatientSearch = self.driver.find_element_by_xpath(PracticeLocators.Patient_search_textbox)
        PatientSearch.click()
        PatientSearch.send_keys(testData.cell(2, 1).value)
        self.driver.find_element_by_xpath("(//*[text()='" + testData.cell(2, 2).value + "'])[1]").click()
        DoctorSearch = self.driver.find_element_by_xpath(PracticeLocators.doctor_search_textbox)
        DoctorSearch.click()
        DoctorSearch.send_keys(scriptData.cell(2, 8).value)
        self.driver.find_element_by_xpath(
            "(//*[text()='" + scriptData.cell(2, 8).value + " " + "Practice'])[2]").click()
        self.driver.find_element_by_xpath(PracticeLocators.NextButton).click()
        self.driver.find_element_by_xpath(PracticeLocators.CreateOnetimeRXButton).click()
        self.driver.find_element_by_name(PracticeLocators.OnetimeSearchMedicine).send_keys(scriptData.cell(2, 3).value)
        time.sleep(2)
        self.driver.find_element_by_xpath("//*[text()='" + scriptData.cell(2, 3).value + "']").click()
        self.driver.find_element_by_xpath(PracticeLocators.AddButton).click()
        self.driver.find_element_by_xpath(PracticeLocators.ProductQuantity).click()
        time.sleep(1)
        self.driver.find_element_by_xpath(PracticeLocators.Quantity).click()
        self.driver.find_element_by_xpath(PracticeLocators.ProductRefilles).click()
        time.sleep(1)
        self.driver.find_element_by_xpath(PracticeLocators.Quantity).click()
        time.sleep(2)
        self.driver.find_element_by_xpath(PracticeLocators.DAWCheckbox).click()
        time.sleep(2)
        instruction = self.driver.find_element_by_xpath(PracticeLocators.productInstruction)
        instruction.click()
        instruction.send_keys(testData.cell(2, 3).value)
        self.driver.find_element_by_xpath(PracticeLocators.allergiesButton).click()
        allergies = self.driver.find_element_by_xpath(PracticeLocators.allergiesTextbox)
        allergies.clear()
        allergies.send_keys(testData.cell(2, 4).value)
        self.driver.find_element_by_xpath(PracticeLocators.doneButton).click()
        self.driver.find_element_by_xpath(PracticeLocators.addDropchartButton).click()
        time.sleep(2)
        element = self.driver.find_element_by_xpath(PracticeLocators.selectDocuments)
        self.driver.execute_script("arguments[0].click()", element)
        self.driver.find_element_by_xpath(PracticeLocators.selectButton).click()
        self.driver.find_element_by_xpath(PracticeLocators.skipPayment).click()
        self.driver.find_element_by_xpath(PracticeLocators.surgeryDate).send_keys(currentDate)
        Notes = self.driver.find_elements(By.XPATH, PracticeLocators.pharmacyNotes)
        if Notes:
            Notes[0].send_keys(testData.cell(2, 5).value)
        else:
            self.driver.find_element_by_xpath(DispenserLocators.addNoteButton).click()
            self.driver.find_element_by_xpath('//textarea[@class="sc-hIVACf cpAwkS"]').send_keys(
                testData.cell(2, 5).value)
            pharmaCheckbox = self.driver.find_elements(By.XPATH, "//label[contains(text(),'Pharmacy')]")
            if pharmaCheckbox:
                pharmaCheckbox[0].click()
            self.driver.find_element_by_xpath(PatientLocators.iframeSaveButton).click()
        createOrderButton = self.driver.find_element_by_xpath(PracticeLocators.submit_CreateOrderButton)
        self.driver.execute_script("arguments[0].click()", createOrderButton)
        time.sleep(7)

    def SubscriptionRXSkipPayment(self):
        self.driver.find_element_by_class_name(PracticeLocators.Add_RX).click()
        PatientSearch = self.driver.find_element_by_xpath(PracticeLocators.Patient_search_textbox)
        PatientSearch.click()
        PatientSearch.send_keys(testData.cell(2, 1).value)
        self.driver.find_element_by_xpath("(//*[text()='" + testData.cell(2, 2).value + "'])[1]").click()
        DoctorSearch = self.driver.find_element_by_xpath(PracticeLocators.doctor_search_textbox)
        DoctorSearch.click()
        DoctorSearch.send_keys(scriptData.cell(2, 8).value)
        self.driver.find_element_by_xpath(
            "(//*[text()='" + scriptData.cell(2, 8).value + " " + "Practice'])[2]").click()
        self.driver.find_element_by_xpath(PracticeLocators.NextButton).click()
        el = self.driver.find_element_by_xpath(PracticeLocators.createSubscriptionRxButton)
        self.driver.execute_script('arguments[0].click()', el)
        self.driver.find_element_by_xpath(PracticeLocators.subscriptionProductSearch).send_keys(scriptData.cell(2, 1).value)
        time.sleep(2)
        self.driver.find_element_by_xpath("//*[text()='" + scriptData.cell(2, 1).value + "']").click()
        self.driver.find_element_by_xpath(PracticeLocators.AddButton).click()
        self.driver.find_element_by_xpath(PracticeLocators.ProductQuantity).click()
        time.sleep(1)
        self.driver.find_element_by_xpath(PracticeLocators.Quantity).click()
        self.driver.find_element_by_xpath(PracticeLocators.ProductRefilles).click()
        time.sleep(1)
        self.driver.find_element_by_xpath(PracticeLocators.Quantity).click()
        time.sleep(2)
        self.driver.find_element_by_xpath(PracticeLocators.DAWCheckbox).click()
        time.sleep(2)
        instruction = self.driver.find_element_by_xpath(PracticeLocators.productInstruction)
        instruction.click()
        instruction.send_keys(testData.cell(2, 3).value)
        self.driver.find_element_by_xpath(PracticeLocators.allergiesButton).click()
        allergies = self.driver.find_element_by_xpath(PracticeLocators.allergiesTextbox)
        allergies.clear()
        allergies.send_keys(testData.cell(2, 4).value)
        self.driver.find_element_by_xpath(PracticeLocators.doneButton).click()
        self.driver.find_element_by_xpath(PracticeLocators.addDropchartButton).click()
        time.sleep(2)
        element = self.driver.find_element_by_xpath(PracticeLocators.selectDocuments)
        self.driver.execute_script("arguments[0].click()", element)
        self.driver.find_element_by_xpath(PracticeLocators.selectButton).click()
        self.driver.find_element_by_xpath(PracticeLocators.skipPayment).click()
        self.driver.find_element_by_xpath(DispenserLocators.selectServiceType).click()
        time.sleep(1)
        self.driver.find_element_by_css_selector(DispenserLocators.pickUpPerson).click()
        self.driver.find_element_by_xpath(PracticeLocators.surgeryDate).send_keys(currentDate)
        Notes = self.driver.find_elements(By.XPATH, PracticeLocators.pharmacyNotes)
        if Notes:
            Notes[0].send_keys(testData.cell(2, 5).value)
        else:
            self.driver.find_element_by_xpath(DispenserLocators.addNoteButton).click()
            self.driver.find_element_by_xpath('//textarea[@class="sc-hIVACf cpAwkS"]').send_keys(
                testData.cell(2, 5).value)
            pharmaCheckbox = self.driver.find_elements(By.XPATH, "//label[contains(text(),'Pharmacy')]")
            if pharmaCheckbox:
                pharmaCheckbox[0].click()
            self.driver.find_element_by_xpath(PatientLocators.iframeSaveButton).click()
        createOrderButton = self.driver.find_element_by_xpath(PracticeLocators.submit_CreateOrderButton)
        self.driver.execute_script("arguments[0].click()", createOrderButton)
        time.sleep(7)

    def SubscriptionOTCSkipPayment(self):
        self.driver.find_element_by_class_name(PracticeLocators.Add_RX).click()
        PatientSearch = self.driver.find_element_by_xpath(PracticeLocators.Patient_search_textbox)
        PatientSearch.click()
        PatientSearch.send_keys(testData.cell(2, 1).value)
        self.driver.find_element_by_xpath("(//*[text()='" + testData.cell(2, 2).value + "'])[1]").click()
        DoctorSearch = self.driver.find_element_by_xpath(PracticeLocators.doctor_search_textbox)
        DoctorSearch.click()
        DoctorSearch.send_keys(scriptData.cell(2, 8).value)
        self.driver.find_element_by_xpath(
            "(//*[text()='" + scriptData.cell(2, 8).value + " " + "Practice'])[2]").click()
        self.driver.find_element_by_xpath(PracticeLocators.NextButton).click()
        el = self.driver.find_element_by_xpath(PracticeLocators.createSubscriptionRxButton)
        self.driver.execute_script('arguments[0].click()', el)
        self.driver.find_element_by_xpath(PracticeLocators.subscriptionProductSearch).send_keys(scriptData.cell(2, 2).value)
        time.sleep(2)
        self.driver.find_element_by_xpath("//*[text()='" + scriptData.cell(2, 2).value + "']").click()
        self.driver.find_element_by_xpath(PracticeLocators.AddButton).click()
        self.driver.find_element_by_xpath(PracticeLocators.ProductQuantity).click()
        time.sleep(1)
        self.driver.find_element_by_xpath(PracticeLocators.Quantity).click()
        self.driver.find_element_by_xpath(PracticeLocators.ProductRefilles).click()
        time.sleep(1)
        self.driver.find_element_by_xpath(PracticeLocators.Quantity).click()
        time.sleep(2)
        self.driver.find_element_by_xpath(PracticeLocators.DAWCheckbox).click()
        time.sleep(2)
        instruction = self.driver.find_element_by_xpath(PracticeLocators.productInstruction)
        instruction.click()
        instruction.send_keys(testData.cell(2, 3).value)
        self.driver.find_element_by_xpath(PracticeLocators.allergiesButton).click()
        allergies = self.driver.find_element_by_xpath(PracticeLocators.allergiesTextbox)
        allergies.clear()
        allergies.send_keys(testData.cell(2, 4).value)
        self.driver.find_element_by_xpath(PracticeLocators.doneButton).click()
        self.driver.find_element_by_xpath(PracticeLocators.addDropchartButton).click()
        time.sleep(2)
        element = self.driver.find_element_by_xpath(PracticeLocators.selectDocuments)
        self.driver.execute_script("arguments[0].click()", element)
        self.driver.find_element_by_xpath(PracticeLocators.selectButton).click()
        self.driver.find_element_by_xpath(PracticeLocators.skipPayment).click()
        self.driver.find_element_by_xpath(PracticeLocators.surgeryDate).send_keys(currentDate)
        Notes = self.driver.find_elements(By.XPATH, PracticeLocators.pharmacyNotes)
        if Notes:
            Notes[0].send_keys(testData.cell(2, 5).value)
        else:
            self.driver.find_element_by_xpath(DispenserLocators.addNoteButton).click()
            self.driver.find_element_by_xpath('//textarea[@class="sc-hIVACf cpAwkS"]').send_keys(
                testData.cell(2, 5).value)
            pharmaCheckbox = self.driver.find_elements(By.XPATH, "//label[contains(text(),'Pharmacy')]")
            if pharmaCheckbox:
                pharmaCheckbox[0].click()
            self.driver.find_element_by_xpath(PatientLocators.iframeSaveButton).click()
        createOrderButton = self.driver.find_element_by_xpath(PracticeLocators.submit_CreateOrderButton)
        self.driver.execute_script("arguments[0].click()", createOrderButton)
        time.sleep(7)

    def SubscriptionCompoundSkipPayment(self):
        self.driver.find_element_by_class_name(PracticeLocators.Add_RX).click()
        PatientSearch = self.driver.find_element_by_xpath(PracticeLocators.Patient_search_textbox)
        PatientSearch.click()
        PatientSearch.send_keys(testData.cell(2, 1).value)
        self.driver.find_element_by_xpath("(//*[text()='" + testData.cell(2, 2).value + "'])[1]").click()
        DoctorSearch = self.driver.find_element_by_xpath(PracticeLocators.doctor_search_textbox)
        DoctorSearch.click()
        DoctorSearch.send_keys(scriptData.cell(2, 8).value)
        self.driver.find_element_by_xpath(
            "(//*[text()='" + scriptData.cell(2, 8).value + " " + "Practice'])[2]").click()
        self.driver.find_element_by_xpath(PracticeLocators.NextButton).click()
        el = self.driver.find_element_by_xpath(PracticeLocators.createSubscriptionRxButton)
        self.driver.execute_script('arguments[0].click()', el)
        self.driver.find_element_by_xpath(PracticeLocators.subscriptionProductSearch).send_keys(scriptData.cell(2, 3).value)
        time.sleep(2)
        self.driver.find_element_by_xpath("//*[text()='" + scriptData.cell(2, 3).value + "']").click()
        self.driver.find_element_by_xpath(PracticeLocators.AddButton).click()
        self.driver.find_element_by_xpath(PracticeLocators.ProductQuantity).click()
        time.sleep(1)
        self.driver.find_element_by_xpath(PracticeLocators.Quantity).click()
        self.driver.find_element_by_xpath(PracticeLocators.ProductRefilles).click()
        time.sleep(1)
        self.driver.find_element_by_xpath(PracticeLocators.Quantity).click()
        time.sleep(2)
        self.driver.find_element_by_xpath(PracticeLocators.DAWCheckbox).click()
        time.sleep(2)
        instruction = self.driver.find_element_by_xpath(PracticeLocators.productInstruction)
        instruction.click()
        instruction.send_keys(testData.cell(2, 3).value)
        ExpiryDate = self.driver.find_elements(By.XPATH, PracticeLocators.surgeryDate)
        if ExpiryDate:
            ExpiryDate[0].send_keys(currentDate)
        self.driver.find_element_by_xpath(PracticeLocators.allergiesButton).click()
        allergies = self.driver.find_element_by_xpath(PracticeLocators.allergiesTextbox)
        allergies.clear()
        allergies.send_keys(testData.cell(2, 4).value)
        self.driver.find_element_by_xpath(PracticeLocators.doneButton).click()
        self.driver.find_element_by_xpath(PracticeLocators.addDropchartButton).click()
        time.sleep(2)
        element = self.driver.find_element_by_xpath(PracticeLocators.selectDocuments)
        self.driver.execute_script("arguments[0].click()", element)
        self.driver.find_element_by_xpath(PracticeLocators.selectButton).click()
        self.driver.find_element_by_xpath(PracticeLocators.skipPayment).click()
        time.sleep(1)
        self.driver.find_element_by_xpath(PracticeLocators.surgeryDate).send_keys(currentDate)
        Notes = self.driver.find_elements(By.XPATH, PracticeLocators.pharmacyNotes)
        if Notes:
            Notes[0].send_keys(testData.cell(2, 5).value)
        else:
            self.driver.find_element_by_xpath(DispenserLocators.addNoteButton).click()
            self.driver.find_element_by_xpath('//textarea[@class="sc-hIVACf cpAwkS"]').send_keys(
                testData.cell(2, 5).value)
            pharmaCheckbox = self.driver.find_elements(By.XPATH, "//label[contains(text(),'Pharmacy')]")
            if pharmaCheckbox:
                pharmaCheckbox[0].click()
            self.driver.find_element_by_xpath(PatientLocators.iframeSaveButton).click()
        createOrderButton = self.driver.find_element_by_xpath(PracticeLocators.submit_CreateOrderButton)
        self.driver.execute_script("arguments[0].click()", createOrderButton)
        time.sleep(7)

    def OnetimeRXProvidePayment(self):
        self.driver.find_element_by_class_name(PracticeLocators.Add_RX).click()
        PatientSearch = self.driver.find_element_by_xpath(PracticeLocators.Patient_search_textbox)
        PatientSearch.click()
        PatientSearch.send_keys(testData.cell(2, 1).value)
        self.driver.find_element_by_xpath("(//*[text()='" + testData.cell(2, 2).value + "'])[1]").click()
        DoctorSearch = self.driver.find_element_by_xpath(PracticeLocators.doctor_search_textbox)
        DoctorSearch.click()
        DoctorSearch.send_keys(scriptData.cell(2, 8).value)
        self.driver.find_element_by_xpath(
            "(//*[text()='" + scriptData.cell(2, 8).value + " " + "Practice'])[2]").click()
        self.driver.find_element_by_xpath(PracticeLocators.NextButton).click()
        self.driver.find_element_by_xpath(PracticeLocators.CreateOnetimeRXButton).click()
        self.driver.find_element_by_name(PracticeLocators.OnetimeSearchMedicine).send_keys(scriptData.cell(2, 1).value)
        time.sleep(2)
        self.driver.find_element_by_xpath("//*[text()='" + scriptData.cell(2, 1).value + "']").click()
        self.driver.find_element_by_xpath(PracticeLocators.AddButton).click()
        self.driver.find_element_by_xpath(PracticeLocators.ProductQuantity).click()
        time.sleep(1)
        self.driver.find_element_by_xpath(PracticeLocators.Quantity).click()
        self.driver.find_element_by_xpath(PracticeLocators.ProductRefilles).click()
        time.sleep(1)
        self.driver.find_element_by_xpath(PracticeLocators.Quantity).click()
        time.sleep(2)
        self.driver.find_element_by_xpath(PracticeLocators.DAWCheckbox).click()
        time.sleep(2)
        instruction = self.driver.find_element_by_xpath(PracticeLocators.productInstruction)
        instruction.click()
        instruction.send_keys(testData.cell(2, 3).value)
        self.driver.find_element_by_xpath(PracticeLocators.allergiesButton).click()
        allergies = self.driver.find_element_by_xpath(PracticeLocators.allergiesTextbox)
        allergies.clear()
        allergies.send_keys(testData.cell(2, 4).value)
        self.driver.find_element_by_xpath(PracticeLocators.doneButton).click()
        self.driver.find_element_by_xpath(PracticeLocators.addDropchartButton).click()
        time.sleep(2)
        element = self.driver.find_element_by_xpath(PracticeLocators.selectDocuments)
        self.driver.execute_script("arguments[0].click()", element)
        self.driver.find_element_by_xpath(PracticeLocators.selectButton).click()
        self.driver.find_element_by_xpath(PracticeLocators.providePayment).click()
        EditPayment = self.driver.find_elements(By.XPATH, DispenserLocators.editPaymentButton)
        if EditPayment:
            EditPayment[0].click()
        cardName = self.driver.find_element_by_name(PracticeLocators.cardName)
        cardName.clear()
        cardName.send_keys(testData.cell(2, 8).value)

        act = ActionChains(self.driver)
        act.key_down(Keys.CONTROL).send_keys("a").key_up(Keys.CONTROL).perform()
        act.key_down(Keys.CONTROL).send_keys("c").key_up(Keys.CONTROL).perform()
        act.send_keys(Keys.TAB).perform()
        act.key_down(Keys.CONTROL).send_keys("v").key_up(Keys.CONTROL).perform()

        cardName.clear()
        cardName.send_keys(testData.cell(2, 7).value)

        cardCVV = self.driver.find_element_by_name(PracticeLocators.cardCVV)
        cardCVV.clear()
        cardCVV.send_keys(testData.cell(2, 9).value)

        Address1 = self.driver.find_element_by_name(PracticeLocators.addressLine1)
        Address1.clear()
        Address1.send_keys(testData.cell(2, 12).value)
        address2 = self.driver.find_element_by_name(PracticeLocators.addressLine2)
        address2.clear()
        address2.send_keys(testData.cell(2, 13).value)
        addressCity = self.driver.find_element_by_name(PracticeLocators.addressCity)
        addressCity.clear()
        addressCity.send_keys(testData.cell(2, 14).value)
        self.driver.find_element_by_xpath(PracticeLocators.addressState).click()
        time.sleep(2)
        self.driver.find_element_by_xpath(PracticeLocators.state).click()
        time.sleep(7)
        addressZipcode = self.driver.find_element_by_name(PracticeLocators.addressZipCode)
        addressZipcode.clear()
        addressZipcode.send_keys(testData.cell(2, 16).value)
        self.driver.find_element_by_xpath(PracticeLocators.continueButton).click()
        self.driver.find_element_by_xpath(DispenserLocators.selectServiceType).click()
        time.sleep(1)
        self.driver.find_element_by_css_selector(DispenserLocators.courierService).click()
        self.driver.find_element_by_xpath(PracticeLocators.surgeryDate).send_keys(currentDate)
        Notes = self.driver.find_elements(By.XPATH, PracticeLocators.pharmacyNotes)
        if Notes:
            Notes[0].send_keys(testData.cell(2, 5).value)
        else:
            self.driver.find_element_by_xpath(DispenserLocators.addNoteButton).click()
            self.driver.find_element_by_xpath('//textarea[@class="sc-hIVACf cpAwkS"]').send_keys(
                testData.cell(2, 5).value)
            pharmaCheckbox = self.driver.find_elements(By.XPATH, "//label[contains(text(),'Pharmacy')]")
            if pharmaCheckbox:
                pharmaCheckbox[0].click()
            self.driver.find_element_by_xpath(PatientLocators.iframeSaveButton).click()
        createOrderButton = self.driver.find_element_by_xpath(PracticeLocators.submit_CreateOrderButton)
        self.driver.execute_script("arguments[0].click()", createOrderButton)
        time.sleep(7)

    def OnetimeOTCProvidePayment(self):
        self.driver.find_element_by_class_name(PracticeLocators.Add_RX).click()
        PatientSearch = self.driver.find_element_by_xpath(PracticeLocators.Patient_search_textbox)
        PatientSearch.click()
        PatientSearch.send_keys(testData.cell(2, 1).value)
        self.driver.find_element_by_xpath("(//*[text()='" + testData.cell(2, 2).value + "'])[1]").click()
        DoctorSearch = self.driver.find_element_by_xpath(PracticeLocators.doctor_search_textbox)
        DoctorSearch.click()
        DoctorSearch.send_keys(scriptData.cell(2, 8).value)
        self.driver.find_element_by_xpath("(//*[text()='" + scriptData.cell(2, 8).value + " " + "Practice'])[2]").click()
        self.driver.find_element_by_xpath(PracticeLocators.NextButton).click()
        self.driver.find_element_by_xpath(PracticeLocators.CreateOnetimeRXButton).click()
        self.driver.find_element_by_name(PracticeLocators.OnetimeSearchMedicine).send_keys(scriptData.cell(2, 2).value)
        time.sleep(2)
        self.driver.find_element_by_xpath("//*[text()='" + scriptData.cell(2, 2).value + "']").click()
        self.driver.find_element_by_xpath(PracticeLocators.AddButton).click()
        self.driver.find_element_by_xpath(PracticeLocators.ProductQuantity).click()
        time.sleep(1)
        self.driver.find_element_by_xpath(PracticeLocators.Quantity).click()
        self.driver.find_element_by_xpath(PracticeLocators.ProductRefilles).click()
        time.sleep(1)
        self.driver.find_element_by_xpath(PracticeLocators.Quantity).click()
        time.sleep(2)
        self.driver.find_element_by_xpath(PracticeLocators.DAWCheckbox).click()
        time.sleep(2)
        instruction = self.driver.find_element_by_xpath(PracticeLocators.productInstruction)
        instruction.click()
        instruction.send_keys(testData.cell(2, 3).value)
        self.driver.find_element_by_xpath(PracticeLocators.allergiesButton).click()
        allergies = self.driver.find_element_by_xpath(PracticeLocators.allergiesTextbox)
        allergies.clear()
        allergies.send_keys(testData.cell(2, 4).value)
        self.driver.find_element_by_xpath(PracticeLocators.doneButton).click()
        self.driver.find_element_by_xpath(PracticeLocators.addDropchartButton).click()
        time.sleep(2)
        element = self.driver.find_element_by_xpath(PracticeLocators.selectDocuments)
        self.driver.execute_script("arguments[0].click()", element)
        self.driver.find_element_by_xpath(PracticeLocators.selectButton).click()
        self.driver.find_element_by_xpath(PracticeLocators.providePayment).click()
        EditPayment = self.driver.find_elements(By.XPATH, DispenserLocators.editPaymentButton)
        if EditPayment:
            EditPayment[0].click()
        cardName = self.driver.find_element_by_name(PracticeLocators.cardName)
        cardName.clear()
        cardName.send_keys(testData.cell(2, 8).value)

        act = ActionChains(self.driver)
        act.key_down(Keys.CONTROL).send_keys("a").key_up(Keys.CONTROL).perform()
        act.key_down(Keys.CONTROL).send_keys("c").key_up(Keys.CONTROL).perform()
        act.send_keys(Keys.TAB).perform()
        act.key_down(Keys.CONTROL).send_keys("v").key_up(Keys.CONTROL).perform()

        cardName.clear()
        cardName.send_keys(testData.cell(2, 7).value)

        cardCVV = self.driver.find_element_by_name(PracticeLocators.cardCVV)
        cardCVV.clear()
        cardCVV.send_keys(testData.cell(2, 9).value)
        Address1 = self.driver.find_element_by_name(PracticeLocators.addressLine1)
        Address1.clear()
        Address1.send_keys(testData.cell(2, 12).value)
        address2 = self.driver.find_element_by_name(PracticeLocators.addressLine2)
        address2.clear()
        address2.send_keys(testData.cell(2, 13).value)
        addressCity = self.driver.find_element_by_name(PracticeLocators.addressCity)
        addressCity.clear()
        addressCity.send_keys(testData.cell(2, 14).value)
        self.driver.find_element_by_xpath(PracticeLocators.addressState).click()
        time.sleep(2)
        self.driver.find_element_by_xpath(PracticeLocators.state).click()
        addressZipcode = self.driver.find_element_by_name(PracticeLocators.addressZipCode)
        addressZipcode.clear()
        addressZipcode.send_keys(testData.cell(2, 16).value)
        self.driver.find_element_by_xpath(PracticeLocators.continueButton).click()
        self.driver.find_element_by_xpath(PracticeLocators.surgeryDate).send_keys(currentDate)
        Notes = self.driver.find_elements(By.XPATH, PracticeLocators.pharmacyNotes)
        if Notes:
            Notes[0].send_keys(testData.cell(2, 5).value)
        else:
            self.driver.find_element_by_xpath(DispenserLocators.addNoteButton).click()
            self.driver.find_element_by_xpath('//textarea[@class="sc-hIVACf cpAwkS"]').send_keys(
                testData.cell(2, 5).value)
            pharmaCheckbox = self.driver.find_elements(By.XPATH, "//label[contains(text(),'Pharmacy')]")
            if pharmaCheckbox:
                pharmaCheckbox[0].click()
            self.driver.find_element_by_xpath(PatientLocators.iframeSaveButton).click()
        createOrderButton = self.driver.find_element_by_xpath(PracticeLocators.submit_CreateOrderButton)
        self.driver.execute_script("arguments[0].click()", createOrderButton)
        time.sleep(7)

    def OnetimeCompoundProvidePayment(self):
        self.driver.find_element_by_class_name(PracticeLocators.Add_RX).click()
        PatientSearch = self.driver.find_element_by_xpath(PracticeLocators.Patient_search_textbox)
        PatientSearch.click()
        PatientSearch.send_keys(testData.cell(2, 1).value)
        self.driver.find_element_by_xpath("(//*[text()='" + testData.cell(2, 2).value + "'])[1]").click()
        DoctorSearch = self.driver.find_element_by_xpath(PracticeLocators.doctor_search_textbox)
        DoctorSearch.click()
        DoctorSearch.send_keys(scriptData.cell(2, 8).value)
        self.driver.find_element_by_xpath("(//*[text()='" + scriptData.cell(2, 8).value + " " + "Practice'])[2]").click()
        self.driver.find_element_by_xpath(PracticeLocators.NextButton).click()
        self.driver.find_element_by_xpath(PracticeLocators.CreateOnetimeRXButton).click()
        self.driver.find_element_by_name(PracticeLocators.OnetimeSearchMedicine).send_keys(scriptData.cell(2, 3).value)
        time.sleep(2)
        self.driver.find_element_by_xpath("//*[text()='" + scriptData.cell(2, 3).value + "']").click()
        self.driver.find_element_by_xpath(PracticeLocators.AddButton).click()
        self.driver.find_element_by_xpath(PracticeLocators.ProductQuantity).click()
        time.sleep(1)
        self.driver.find_element_by_xpath(PracticeLocators.Quantity).click()
        self.driver.find_element_by_xpath(PracticeLocators.ProductRefilles).click()
        time.sleep(1)
        self.driver.find_element_by_xpath(PracticeLocators.Quantity).click()
        time.sleep(2)
        self.driver.find_element_by_xpath(PracticeLocators.DAWCheckbox).click()
        time.sleep(2)
        instruction = self.driver.find_element_by_xpath(PracticeLocators.productInstruction)
        instruction.click()
        instruction.send_keys(testData.cell(2, 3).value)
        self.driver.find_element_by_xpath(PracticeLocators.allergiesButton).click()
        allergies = self.driver.find_element_by_xpath(PracticeLocators.allergiesTextbox)
        allergies.clear()
        allergies.send_keys(testData.cell(2, 4).value)
        self.driver.find_element_by_xpath(PracticeLocators.doneButton).click()
        self.driver.find_element_by_xpath(PracticeLocators.addDropchartButton).click()
        time.sleep(2)
        element = self.driver.find_element_by_xpath(PracticeLocators.selectDocuments)
        self.driver.execute_script("arguments[0].click()", element)
        self.driver.find_element_by_xpath(PracticeLocators.selectButton).click()
        self.driver.find_element_by_xpath(PracticeLocators.providePayment).click()
        EditPayment = self.driver.find_elements(By.XPATH, DispenserLocators.editPaymentButton)
        if EditPayment:
            EditPayment[0].click()
        cardName = self.driver.find_element_by_name(PracticeLocators.cardName)
        cardName.clear()
        cardName.send_keys(testData.cell(2, 8).value)

        act = ActionChains(self.driver)
        act.key_down(Keys.CONTROL).send_keys("a").key_up(Keys.CONTROL).perform()
        act.key_down(Keys.CONTROL).send_keys("c").key_up(Keys.CONTROL).perform()
        act.send_keys(Keys.TAB).perform()
        act.key_down(Keys.CONTROL).send_keys("v").key_up(Keys.CONTROL).perform()

        cardName.clear()
        cardName.send_keys(testData.cell(2, 7).value)

        cardCVV = self.driver.find_element_by_name(PracticeLocators.cardCVV)
        cardCVV.clear()
        cardCVV.send_keys(testData.cell(2, 9).value)
        Address1 = self.driver.find_element_by_name(PracticeLocators.addressLine1)
        Address1.clear()
        Address1.send_keys(testData.cell(2, 12).value)
        address2 = self.driver.find_element_by_name(PracticeLocators.addressLine2)
        address2.clear()
        address2.send_keys(testData.cell(2, 13).value)
        addressCity = self.driver.find_element_by_name(PracticeLocators.addressCity)
        addressCity.clear()
        addressCity.send_keys(testData.cell(2, 14).value)
        self.driver.find_element_by_xpath(PracticeLocators.addressState).click()
        time.sleep(2)
        self.driver.find_element_by_xpath(PracticeLocators.state).click()
        addressZipcode = self.driver.find_element_by_name(PracticeLocators.addressZipCode)
        addressZipcode.clear()
        addressZipcode.send_keys(testData.cell(2, 16).value)
        self.driver.find_element_by_xpath(PracticeLocators.continueButton).click()
        self.driver.find_element_by_xpath(PracticeLocators.surgeryDate).send_keys(currentDate)
        Notes = self.driver.find_elements(By.XPATH, PracticeLocators.pharmacyNotes)
        if Notes:
            Notes[0].send_keys(testData.cell(2, 5).value)
        else:
            self.driver.find_element_by_xpath(DispenserLocators.addNoteButton).click()
            self.driver.find_element_by_xpath('//textarea[@class="sc-hIVACf cpAwkS"]').send_keys(
                testData.cell(2, 5).value)
            pharmaCheckbox = self.driver.find_elements(By.XPATH, "//label[contains(text(),'Pharmacy')]")
            if pharmaCheckbox:
                pharmaCheckbox[0].click()
            self.driver.find_element_by_xpath(PatientLocators.iframeSaveButton).click()
        createOrderButton = self.driver.find_element_by_xpath(PracticeLocators.submit_CreateOrderButton)
        self.driver.execute_script("arguments[0].click()", createOrderButton)
        time.sleep(7)

    def SubscriptionRXProvidePayment(self):
        self.driver.find_element_by_class_name(PracticeLocators.Add_RX).click()
        PatientSearch = self.driver.find_element_by_xpath(PracticeLocators.Patient_search_textbox)
        PatientSearch.click()
        PatientSearch.send_keys(testData.cell(2, 1).value)
        self.driver.find_element_by_xpath("(//*[text()='" + testData.cell(2, 2).value + "'])[1]").click()
        DoctorSearch = self.driver.find_element_by_xpath(PracticeLocators.doctor_search_textbox)
        DoctorSearch.click()
        DoctorSearch.send_keys(scriptData.cell(2, 8).value)
        self.driver.find_element_by_xpath("(//*[text()='" + scriptData.cell(2, 8).value + " " + "Practice'])[2]").click()
        self.driver.find_element_by_xpath(PracticeLocators.NextButton).click()
        time.sleep(2)
        el = self.driver.find_element_by_xpath(PracticeLocators.createSubscriptionRxButton)
        self.driver.execute_script('arguments[0].click()', el)
        self.driver.find_element_by_xpath(PracticeLocators.subscriptionProductSearch).send_keys(scriptData.cell(2, 1).value)
        time.sleep(2)
        self.driver.find_element_by_xpath("//*[text()='" + scriptData.cell(2, 1).value + "']").click()
        self.driver.find_element_by_xpath(PracticeLocators.AddButton).click()
        self.driver.find_element_by_xpath(PracticeLocators.ProductQuantity).click()
        time.sleep(1)
        self.driver.find_element_by_xpath(PracticeLocators.Quantity).click()
        self.driver.find_element_by_xpath(PracticeLocators.ProductRefilles).click()
        time.sleep(1)
        self.driver.find_element_by_xpath(PracticeLocators.Quantity).click()
        time.sleep(2)
        self.driver.find_element_by_xpath(PracticeLocators.DAWCheckbox).click()
        time.sleep(2)
        instruction = self.driver.find_element_by_xpath(PracticeLocators.productInstruction)
        instruction.click()
        instruction.send_keys(testData.cell(2, 3).value)
        self.driver.find_element_by_xpath(PracticeLocators.allergiesButton).click()
        allergies = self.driver.find_element_by_xpath(PracticeLocators.allergiesTextbox)
        allergies.clear()
        allergies.send_keys(testData.cell(2, 4).value)
        self.driver.find_element_by_xpath(PracticeLocators.doneButton).click()
        self.driver.find_element_by_xpath(PracticeLocators.addDropchartButton).click()
        time.sleep(2)
        element = self.driver.find_element_by_xpath(PracticeLocators.selectDocuments)
        self.driver.execute_script("arguments[0].click()", element)
        self.driver.find_element_by_xpath(PracticeLocators.selectButton).click()
        self.driver.find_element_by_xpath(PracticeLocators.providePayment).click()
        EditPayment = self.driver.find_elements(By.XPATH, DispenserLocators.editPaymentButton)
        if EditPayment:
            EditPayment[0].click()
        cardName = self.driver.find_element_by_name(PracticeLocators.cardName)
        cardName.clear()
        cardName.send_keys(testData.cell(2, 8).value)

        act = ActionChains(self.driver)
        act.key_down(Keys.CONTROL).send_keys("a").key_up(Keys.CONTROL).perform()
        act.key_down(Keys.CONTROL).send_keys("c").key_up(Keys.CONTROL).perform()
        act.send_keys(Keys.TAB).perform()
        act.key_down(Keys.CONTROL).send_keys("v").key_up(Keys.CONTROL).perform()

        cardName.clear()
        cardName.send_keys(testData.cell(2, 7).value)

        cardCVV = self.driver.find_element_by_name(PracticeLocators.cardCVV)
        cardCVV.clear()
        cardCVV.send_keys(testData.cell(2, 9).value)
        Address1 = self.driver.find_element_by_name(PracticeLocators.addressLine1)
        Address1.clear()
        Address1.send_keys(testData.cell(2, 12).value)
        address2 = self.driver.find_element_by_name(PracticeLocators.addressLine2)
        address2.clear()
        address2.send_keys(testData.cell(2, 13).value)
        addressCity = self.driver.find_element_by_name(PracticeLocators.addressCity)
        addressCity.clear()
        addressCity.send_keys(testData.cell(2, 14).value)
        self.driver.find_element_by_xpath(PracticeLocators.addressState).click()
        time.sleep(2)
        self.driver.find_element_by_xpath(PracticeLocators.state).click()
        addressZipcode = self.driver.find_element_by_name(PracticeLocators.addressZipCode)
        addressZipcode.clear()
        addressZipcode.send_keys(testData.cell(2, 16).value)
        self.driver.find_element_by_xpath(PracticeLocators.continueButton).click()
        self.driver.find_element_by_xpath(PracticeLocators.surgeryDate).send_keys(currentDate)
        Notes = self.driver.find_elements(By.XPATH, PracticeLocators.pharmacyNotes)
        if Notes:
            Notes[0].send_keys(testData.cell(2, 5).value)
        else:
            self.driver.find_element_by_xpath(DispenserLocators.addNoteButton).click()
            self.driver.find_element_by_xpath('//textarea[@class="sc-hIVACf cpAwkS"]').send_keys(
                testData.cell(2, 5).value)
            pharmaCheckbox = self.driver.find_elements(By.XPATH, "//label[contains(text(),'Pharmacy')]")
            if pharmaCheckbox:
                pharmaCheckbox[0].click()
            self.driver.find_element_by_xpath(PatientLocators.iframeSaveButton).click()
        createOrderButton = self.driver.find_element_by_xpath(PracticeLocators.submit_CreateOrderButton)
        self.driver.execute_script("arguments[0].click()", createOrderButton)
        time.sleep(7)

    def SubscriptionOTCProvidePayment(self):
        self.driver.find_element_by_class_name(PracticeLocators.Add_RX).click()
        PatientSearch = self.driver.find_element_by_xpath(PracticeLocators.Patient_search_textbox)
        PatientSearch.click()
        PatientSearch.send_keys(testData.cell(2, 1).value)
        self.driver.find_element_by_xpath("(//*[text()='" + testData.cell(2, 2).value + "'])[1]").click()
        DoctorSearch = self.driver.find_element_by_xpath(PracticeLocators.doctor_search_textbox)
        DoctorSearch.click()
        DoctorSearch.send_keys(scriptData.cell(2, 8).value)
        self.driver.find_element_by_xpath("(//*[text()='" + scriptData.cell(2, 8).value + " " + "Practice'])[2]").click()
        self.driver.find_element_by_xpath(PracticeLocators.NextButton).click()
        time.sleep(2)
        el = self.driver.find_element_by_xpath(PracticeLocators.createSubscriptionRxButton)
        self.driver.execute_script('arguments[0].click()', el)
        self.driver.find_element_by_xpath(PracticeLocators.subscriptionProductSearch).send_keys(scriptData.cell(2, 2).value)
        time.sleep(2)
        self.driver.find_element_by_xpath("//*[text()='" + scriptData.cell(2, 2).value + "']").click()
        self.driver.find_element_by_xpath(PracticeLocators.AddButton).click()
        self.driver.find_element_by_xpath(PracticeLocators.ProductQuantity).click()
        time.sleep(1)
        self.driver.find_element_by_xpath(PracticeLocators.Quantity).click()
        self.driver.find_element_by_xpath(PracticeLocators.ProductRefilles).click()
        time.sleep(1)
        self.driver.find_element_by_xpath(PracticeLocators.Quantity).click()
        time.sleep(2)
        self.driver.find_element_by_xpath(PracticeLocators.DAWCheckbox).click()
        time.sleep(2)
        instruction = self.driver.find_element_by_xpath(PracticeLocators.productInstruction)
        instruction.click()
        instruction.send_keys(testData.cell(2, 3).value)
        self.driver.find_element_by_xpath(PracticeLocators.allergiesButton).click()
        allergies = self.driver.find_element_by_xpath(PracticeLocators.allergiesTextbox)
        allergies.clear()
        allergies.send_keys(testData.cell(2, 4).value)
        self.driver.find_element_by_xpath(PracticeLocators.doneButton).click()
        self.driver.find_element_by_xpath(PracticeLocators.addDropchartButton).click()
        time.sleep(2)
        element = self.driver.find_element_by_xpath(PracticeLocators.selectDocuments)
        self.driver.execute_script("arguments[0].click()", element)
        self.driver.find_element_by_xpath(PracticeLocators.selectButton).click()
        self.driver.find_element_by_xpath(PracticeLocators.providePayment).click()
        EditPayment = self.driver.find_elements(By.XPATH, DispenserLocators.editPaymentButton)
        if EditPayment:
            EditPayment[0].click()
        cardName = self.driver.find_element_by_name(PracticeLocators.cardName)
        cardName.clear()
        cardName.send_keys(testData.cell(2, 8).value)

        act = ActionChains(self.driver)
        act.key_down(Keys.CONTROL).send_keys("a").key_up(Keys.CONTROL).perform()
        act.key_down(Keys.CONTROL).send_keys("c").key_up(Keys.CONTROL).perform()
        act.send_keys(Keys.TAB).perform()
        act.key_down(Keys.CONTROL).send_keys("v").key_up(Keys.CONTROL).perform()

        cardName.clear()
        cardName.send_keys(testData.cell(2, 7).value)

        cardCVV = self.driver.find_element_by_name(PracticeLocators.cardCVV)
        cardCVV.clear()
        cardCVV.send_keys(testData.cell(2, 9).value)
        Address1 = self.driver.find_element_by_name(PracticeLocators.addressLine1)
        Address1.clear()
        Address1.send_keys(testData.cell(2, 12).value)
        address2 = self.driver.find_element_by_name(PracticeLocators.addressLine2)
        address2.clear()
        address2.send_keys(testData.cell(2, 13).value)
        addressCity = self.driver.find_element_by_name(PracticeLocators.addressCity)
        addressCity.clear()
        addressCity.send_keys(testData.cell(2, 14).value)
        self.driver.find_element_by_xpath(PracticeLocators.addressState).click()
        time.sleep(2)
        self.driver.find_element_by_xpath(PracticeLocators.state).click()
        addressZipcode = self.driver.find_element_by_name(PracticeLocators.addressZipCode)
        addressZipcode.clear()
        addressZipcode.send_keys(testData.cell(2, 16).value)
        self.driver.find_element_by_xpath(PracticeLocators.continueButton).click()
        self.driver.find_element_by_xpath(PracticeLocators.surgeryDate).send_keys(currentDate)
        Notes = self.driver.find_elements(By.XPATH, PracticeLocators.pharmacyNotes)
        if Notes:
            Notes[0].send_keys(testData.cell(2, 5).value)
        else:
            self.driver.find_element_by_xpath(DispenserLocators.addNoteButton).click()
            self.driver.find_element_by_xpath('//textarea[@class="sc-hIVACf cpAwkS"]').send_keys(
                testData.cell(2, 5).value)
            pharmaCheckbox = self.driver.find_elements(By.XPATH, "//label[contains(text(),'Pharmacy')]")
            if pharmaCheckbox:
                pharmaCheckbox[0].click()
            self.driver.find_element_by_xpath(PatientLocators.iframeSaveButton).click()
        createOrderButton = self.driver.find_element_by_xpath(PracticeLocators.submit_CreateOrderButton)
        self.driver.execute_script("arguments[0].click()", createOrderButton)
        time.sleep(7)

    def SubscriptionCompoundProvidePayment(self):
        self.driver.find_element_by_class_name(PracticeLocators.Add_RX).click()
        PatientSearch = self.driver.find_element_by_xpath(PracticeLocators.Patient_search_textbox)
        PatientSearch.click()
        PatientSearch.send_keys(testData.cell(2, 1).value)
        self.driver.find_element_by_xpath("(//*[text()='" + testData.cell(2, 2).value + "'])[1]").click()
        DoctorSearch = self.driver.find_element_by_xpath(PracticeLocators.doctor_search_textbox)
        DoctorSearch.click()
        DoctorSearch.send_keys(scriptData.cell(2, 8).value)
        self.driver.find_element_by_xpath("(//*[text()='" + scriptData.cell(2, 8).value + " " + "Practice'])[2]").click()
        self.driver.find_element_by_xpath(PracticeLocators.NextButton).click()
        time.sleep(2)
        el = self.driver.find_element_by_xpath(PracticeLocators.createSubscriptionRxButton)
        self.driver.execute_script('arguments[0].click()', el)
        self.driver.find_element_by_xpath(PracticeLocators.subscriptionProductSearch).send_keys(scriptData.cell(2, 3).value)
        time.sleep(2)
        self.driver.find_element_by_xpath("//*[text()='" + scriptData.cell(2, 3).value + "']").click()
        self.driver.find_element_by_xpath(PracticeLocators.AddButton).click()
        self.driver.find_element_by_xpath(PracticeLocators.ProductQuantity).click()
        time.sleep(1)
        self.driver.find_element_by_xpath(PracticeLocators.Quantity).click()
        self.driver.find_element_by_xpath(PracticeLocators.ProductRefilles).click()
        time.sleep(1)
        self.driver.find_element_by_xpath(PracticeLocators.Quantity).click()
        time.sleep(2)
        self.driver.find_element_by_xpath(PracticeLocators.DAWCheckbox).click()
        time.sleep(2)
        instruction = self.driver.find_element_by_xpath(PracticeLocators.productInstruction)
        instruction.click()
        instruction.send_keys(testData.cell(2, 3).value)
        ExpiryDate = self.driver.find_elements(By.XPATH, PracticeLocators.surgeryDate)
        if ExpiryDate:
            ExpiryDate[0].send_keys(currentDate)
        self.driver.find_element_by_xpath(PracticeLocators.allergiesButton).click()
        allergies = self.driver.find_element_by_xpath(PracticeLocators.allergiesTextbox)
        allergies.clear()
        allergies.send_keys(testData.cell(2, 4).value)
        self.driver.find_element_by_xpath(PracticeLocators.doneButton).click()
        self.driver.find_element_by_xpath(PracticeLocators.addDropchartButton).click()
        time.sleep(2)
        element = self.driver.find_element_by_xpath(PracticeLocators.selectDocuments)
        self.driver.execute_script("arguments[0].click()", element)
        self.driver.find_element_by_xpath(PracticeLocators.selectButton).click()
        self.driver.find_element_by_xpath(PracticeLocators.providePayment).click()
        EditPayment = self.driver.find_elements(By.XPATH, DispenserLocators.editPaymentButton)
        if EditPayment:
            EditPayment[0].click()
        cardName = self.driver.find_element_by_name(PracticeLocators.cardName)
        cardName.clear()
        cardName.send_keys(testData.cell(2, 8).value)

        act = ActionChains(self.driver)
        act.key_down(Keys.CONTROL).send_keys("a").key_up(Keys.CONTROL).perform()
        act.key_down(Keys.CONTROL).send_keys("c").key_up(Keys.CONTROL).perform()
        act.send_keys(Keys.TAB).perform()
        act.key_down(Keys.CONTROL).send_keys("v").key_up(Keys.CONTROL).perform()

        cardName.clear()
        cardName.send_keys(testData.cell(2, 7).value)

        cardCVV = self.driver.find_element_by_name(PracticeLocators.cardCVV)
        cardCVV.clear()
        cardCVV.send_keys(testData.cell(2, 9).value)
        Address1 = self.driver.find_element_by_name(PracticeLocators.addressLine1)
        Address1.clear()
        Address1.send_keys(testData.cell(2, 12).value)
        address2 = self.driver.find_element_by_name(PracticeLocators.addressLine2)
        address2.clear()
        address2.send_keys(testData.cell(2, 13).value)
        addressCity = self.driver.find_element_by_name(PracticeLocators.addressCity)
        addressCity.clear()
        addressCity.send_keys(testData.cell(2, 14).value)
        self.driver.find_element_by_xpath(PracticeLocators.addressState).click()
        time.sleep(2)
        self.driver.find_element_by_xpath(PracticeLocators.state).click()
        addressZipcode = self.driver.find_element_by_name(PracticeLocators.addressZipCode)
        addressZipcode.clear()
        addressZipcode.send_keys(testData.cell(2, 16).value)
        self.driver.find_element_by_xpath(PracticeLocators.continueButton).click()
        self.driver.find_element_by_xpath(PracticeLocators.surgeryDate).send_keys(currentDate)
        Notes = self.driver.find_elements(By.XPATH, PracticeLocators.pharmacyNotes)
        if Notes:
            Notes[0].send_keys(testData.cell(2, 5).value)
        else:
            self.driver.find_element_by_xpath(DispenserLocators.addNoteButton).click()
            self.driver.find_element_by_xpath('//textarea[@class="sc-hIVACf cpAwkS"]').send_keys(
                testData.cell(2, 5).value)
            pharmaCheckbox = self.driver.find_elements(By.XPATH, "//label[contains(text(),'Pharmacy')]")
            if pharmaCheckbox:
                pharmaCheckbox[0].click()
            self.driver.find_element_by_xpath(PatientLocators.iframeSaveButton).click()
        createOrderButton = self.driver.find_element_by_xpath(PracticeLocators.submit_CreateOrderButton)
        self.driver.execute_script("arguments[0].click()", createOrderButton)
        time.sleep(7)

    def EditOrder(self):
        self.driver.find_element_by_link_text('Orders').click()
        self.driver.find_element_by_xpath('//*[@class="table"]//*[a]').click()
        self.driver.find_element_by_link_text('Edit Contents').click()
        self.driver.find_element_by_xpath('//*[@class="sc-hXRMBi eQtMFe"]').click()
        self.driver.find_element_by_xpath(PracticeLocators.searchForMedication).click()
        time.sleep(3)
        self.driver.find_element_by_xpath("//*[text()='150 Rx']").click()
        self.driver.find_element_by_xpath(PracticeLocators.AddButton).click()
        time.sleep(1)
        self.driver.find_element_by_xpath(PracticeLocators.skipPayment).click()
        self.driver.find_element_by_xpath(PracticeLocators.updateOrderButton).click()
        time.sleep(7)
        if "You're all set!" in self.driver.page_source:
            self.driver.find_element_by_partial_link_text("Return to Dashboard").click()
        else:
            print("\nOrder not created")
        self.driver.find_element_by_class_name('account-link-label').click()
        self.driver.find_element_by_link_text('Sign Out').click()
        self.driver.close()

    def EditPatientDetails(self):
        self.driver.find_element_by_css_selector(DispenserLocators.patientSearch).send_keys(testData.cell(2, 1).value)
        time.sleep(3)
        self.driver.find_element_by_css_selector(DispenserLocators.firstOrder).click()
        self.driver.find_element_by_xpath(DispenserLocators.editButton).click()
        cardName = self.driver.find_element_by_name(PracticeLocators.cardName)
        cardName.clear()
        cardName.send_keys(testData.cell(2, 8).value)
        act = ActionChains(self.driver)
        act.key_down(Keys.CONTROL).send_keys("a").key_up(Keys.CONTROL).perform()
        act.key_down(Keys.CONTROL).send_keys("c").key_up(Keys.CONTROL).perform()
        act.send_keys(Keys.TAB).perform()
        act.key_down(Keys.CONTROL).send_keys("v").key_up(Keys.CONTROL).perform()
        cardName.clear()
        cardName.send_keys(testData.cell(2, 7).value)
        cardCVV = self.driver.find_element_by_name(PracticeLocators.cardCVV)
        cardCVV.clear()
        cardCVV.send_keys(testData.cell(2, 9).value)
        self.driver.find_element_by_name(PracticeLocators.addressLine1).send_keys(testData.cell(2, 12).value)
        self.driver.find_element_by_name(PracticeLocators.addressLine2).send_keys(testData.cell(2, 13).value)
        self.driver.find_element_by_name(PracticeLocators.addressCity).send_keys(testData.cell(2, 14).value)
        self.driver.find_element_by_xpath(PracticeLocators.addressState).click()
        time.sleep(2)
        self.driver.find_element_by_xpath(PracticeLocators.state).click()
        self.driver.find_element_by_name(PracticeLocators.addressZipCode).send_keys(testData.cell(2, 16).value)
        self.driver.find_element_by_xpath(DispenserLocators.saveAndExitButton).click()
        self.driver.implicitly_wait(10)
        assert "Order has been successfully updated."
        button = self.driver.find_element_by_xpath(PracticeLocators.dismissButton)
        self.driver.execute_script("arguments[0].click()", button)
        self.driver.quit()

    def CompleteOrder(self):
        self.driver.find_element_by_css_selector(DispenserLocators.patientSearch).send_keys(testData.cell(2, 1).value)
        time.sleep(3)
        self.driver.find_element_by_css_selector(DispenserLocators.firstOrder).click()
        self.driver.find_element_by_xpath(DispenserLocators.selectActionDropdown).click()
        time.sleep(2)
        self.driver.find_element_by_xpath(DispenserLocators.completeValue).click()
        self.driver.find_element_by_class_name('form-control').send_keys('Patient completed the treatment.')
        self.driver.find_element_by_xpath(PracticeLocators.submitButton).click()
        time.sleep(2)
        assert "You have successfully completed this order"
        button = self.driver.find_element_by_xpath(PracticeLocators.dismissButton)
        self.driver.execute_script("arguments[0].click()", button)
        self.driver.quit()

    def CancelOrder(self):
        self.driver.find_element_by_css_selector(DispenserLocators.patientSearch).send_keys(testData.cell(2, 1).value)
        time.sleep(3)
        self.driver.find_element_by_css_selector(DispenserLocators.firstOrder).click()
        self.driver.find_element_by_xpath(DispenserLocators.selectActionDropdown).click()
        time.sleep(2)
        self.driver.find_element_by_xpath(DispenserLocators.cancelValue).click()
        self.driver.find_element_by_class_name('form-control').send_keys('I do not need this order.')
        self.driver.find_element_by_xpath(PracticeLocators.submitButton).click()
        time.sleep(2)
        assert "You have successfully canceled this order"
        button = self.driver.find_element_by_xpath(PracticeLocators.dismissButton)
        self.driver.execute_script("arguments[0].click()", button)
        self.driver.quit()

    def SendOutOfNetwork(self):
        self.driver.find_element_by_css_selector(DispenserLocators.patientSearch).send_keys(testData.cell(2, 1).value)
        time.sleep(3)
        self.driver.find_element_by_css_selector(DispenserLocators.firstOrder).click()
        self.driver.find_element_by_xpath(DispenserLocators.selectActionDropdown).click()
        time.sleep(2)
        self.driver.find_element_by_xpath(DispenserLocators.sendOutOfNetwork).click()
        self.driver.find_element_by_class_name('form-control').send_keys('Order send out of network.')
        self.driver.find_element_by_xpath(PracticeLocators.submitButton).click()
        time.sleep(2)
        assert "You have successfully sent this order out of network"
        button = self.driver.find_element_by_xpath(PracticeLocators.dismissButton)
        self.driver.execute_script("arguments[0].click()", button)
        self.driver.quit()

    def ApproveOrderFromPractice(self):
        assert self.driver.find_element_by_xpath(DispenserLocators.verifyOrderDate)
        assert self.driver.find_element_by_xpath("(//tr[@class='table-row'])[1]//td[3][text()='" + testData.cell(2, 1).value + "']")
        self.driver.find_element_by_xpath(DispenserLocators.approveButton).click()
        time.sleep(2)
        assert "Please confirm that you approve the selected prescriptions."
        time.sleep(1)
        self.driver.find_element_by_xpath(DispenserLocators.yesButton).click()
        time.sleep(1)
        assert "You have successfully approved the selected prescriptions!"
        self.driver.find_element_by_xpath(PracticeLocators.closeButton).click()
        self.driver.close()

    def PatientApprovalAndTransfer(self):
        self.driver.find_element_by_css_selector(DispenserLocators.patientSearch).send_keys(testData.cell(2, 1).value)
        time.sleep(3)
        self.driver.find_element_by_css_selector(DispenserLocators.firstOrder).click()
        self.driver.find_element_by_xpath(DispenserLocators.confirmApprovalButton).click()
        time.sleep(1)
        assert "Patient payment approval has been sucessfully captured."
        dissmissButton = self.driver.find_element_by_xpath(PracticeLocators.dismissButton)
        self.driver.execute_script("arguments[0].click()", dissmissButton)
        self.driver.find_element_by_xpath(DispenserLocators.transferOrderButton).click()
        time.sleep(1)
        assert "Have you attached the proper document(s) for this order?"
        self.driver.find_element_by_xpath(DispenserLocators.yesButton).click()
        time.sleep(1)
        assert "This order has been successfully transferred."
        time.sleep(2)
        Button = self.driver.find_element_by_xpath(PracticeLocators.dismissButton)
        self.driver.execute_script("arguments[0].click()", Button)
        self.driver.quit()

    def ProcessPayment(self):
        self.driver.find_element_by_css_selector(DispenserLocators.patientSearch).send_keys(testData.cell(2, 1).value)
        time.sleep(3)
        self.driver.find_element_by_css_selector(DispenserLocators.firstOrder).click()
        self.driver.implicitly_wait(10)
        self.driver.find_element_by_xpath(DispenserLocators.processPaymentButton).click()
        time.sleep(3)
        assert "Congratulations, payment has been successfully processed!"
