from datetime import date
import time
from faker import Faker
from openpyxl import load_workbook
from Locators.Locators import Locators

FilePath = "C:/Users/Administrator/PycharmProject/LegrandePython/TestData/Data.xlsx"
datafile = load_workbook(FilePath)
datasheet = datafile.get_sheet_by_name('Test Data')
loginSheet = datafile.get_sheet_by_name("Login Credentials")

faker = Faker()
today = date.today()
currentDate = today.strftime("%m/%d/%Y")
FirstName = faker.first_name()
LastName = faker.last_name()
PhoneNumber = faker.phone_number()
EmailAddress = FirstName + "." + LastName + "@mailinator.com"


class CommanFlow:
    def __init__(self, driver):
        self.driver = driver

    def CreatePatient(self):
        self.driver.find_element_by_class_name(Locators.addPersonButton).click()
        self.driver.find_element_by_name(Locators.firstName).send_keys(FirstName)
        self.driver.find_element_by_name(Locators.lastName).send_keys(LastName)
        self.driver.find_element_by_name(Locators.birthDate).send_keys(currentDate)
        self.driver.find_element_by_name(Locators.phoneNumber).send_keys(PhoneNumber)
        self.driver.find_element_by_name(Locators.Email).send_keys(EmailAddress.lower())
        self.driver.find_element_by_xpath(Locators.createAccountButton).click()
        time.sleep(5)
        if "Congratulations, you have successfully created a new Patient Account." in self.driver.page_source:
            self.driver.find_element_by_xpath(Locators.closeButton).click()
            datasheet.cell(2, 1).value = FirstName + " " + LastName
            datasheet.cell(2, 2).value = FirstName + " " + LastName + " (" + currentDate + ")"
            datasheet.cell(2, 3).value = EmailAddress.lower()
            datafile.save(FilePath)
            print("\nPatient Created Successfully")
        else:
            print("\nPatient not Created")
        self.driver.close()

    def CreateUser(self):
        self.driver.find_element_by_class_name(Locators.accountLinkLabel).click()
        self.driver.find_element_by_link_text(Locators.manageUser).click()
        self.driver.find_element_by_xpath(Locators.addUserButton).click()
        self.driver.find_element_by_name(Locators.firstName).send_keys(FirstName)
        self.driver.find_element_by_name(Locators.lastName).send_keys(LastName)
        self.driver.find_element_by_name(Locators.Email).send_keys(EmailAddress.lower())
        self.driver.find_element_by_name(Locators.phoneNumber).send_keys(PhoneNumber)
        self.driver.find_element_by_class_name(Locators.selectAccountType).click()
        time.sleep(2)
        self.driver.find_element_by_xpath(Locators.clerkOption).click()
        time.sleep(1)
        self.driver.find_element_by_xpath(Locators.createAccountButton).click()
        time.sleep(3)
        if "Congratulations. You have successfully created new user profile." in self.driver.page_source:
            self.driver.find_element_by_xpath(Locators.dismissButton).click()
            print("User created successfully")
        else:
            print("User not created")
        self.driver.close()

    def PatientMainSearch(self):
        self.driver.find_element_by_class_name(Locators.mainPatientSearch).click()
        self.driver.find_element_by_xpath(Locators.mainSearchTextbox).send_keys(datasheet.cell(2, 1).value)
        self.driver.find_element_by_class_name(Locators.mainSearchButton).click()
        try:
            self.driver.find_element_by_xpath(Locators.tableRow).click()
            try:
                self.driver.find_element_by_link_text(Locators.viewDetails).click()
            except:
                print("\nOrder not created for " + datasheet.cell(2, 1).value + ".")
        except:
            print("\nPatient: " + datasheet.cell(2, 1).value + " not found...")
        self.driver.close()

    def ChangeProductPrice(self):
        self.driver.find_element_by_class_name(Locators.accountLinkLabel).click()
        self.driver.find_element_by_link_text(Locators.productList).click()
        time.sleep(2)
        self.driver.find_element_by_xpath(Locators.tableRow).click()
        self.driver.find_element_by_xpath(Locators.updateButton).click()
        self.driver.find_element_by_xpath(Locators.changePriceButton).click()
        if "You have successfully updated the price of 100 Compound" in self.driver.page_source:
            self.driver.find_element_by_xpath(Locators.closeButton).click()
            print('\nProduct price changed successfully')
        else:
            print('\nProduct price not changed')
        self.driver.close()

    def OnetimeRXSkipPayment(self):
        self.driver.find_element_by_class_name(Locators.Add_RX).click()
        PatientSearch = self.driver.find_element_by_xpath(Locators.Patient_search_textbox)
        PatientSearch.click()
        PatientSearch.send_keys(datasheet.cell(2, 1).value)
        self.driver.find_element_by_xpath("(//*[text()='" + datasheet.cell(2, 2).value + "'])[1]").click()
        DoctorSearch = self.driver.find_element_by_xpath(Locators.doctor_search_textbox)
        DoctorSearch.click()
        DoctorSearch.send_keys(datasheet.cell(2, 4).value)
        self.driver.find_element_by_xpath("(//*[text()='" + datasheet.cell(2, 4).value + " " + "Practice'])[2]").click()
        self.driver.find_element_by_xpath(Locators.NextButton).click()
        self.driver.find_element_by_xpath(Locators.CreateOnetimeRXButton).click()
        self.driver.find_element_by_name(Locators.OnetimeSearchMedicine).click()
        time.sleep(3)
        Product = self.driver.find_element_by_xpath("//*[text()='" + datasheet.cell(2, 6).value + "']")
        Product.click()
        self.driver.find_element_by_xpath(Locators.AddButton).click()
        self.driver.find_element_by_xpath(Locators.ProductQuantity).click()
        time.sleep(1)
        self.driver.find_element_by_xpath(Locators.Quantity).click()
        self.driver.find_element_by_xpath(Locators.ProductRefilles).click()
        time.sleep(1)
        self.driver.find_element_by_xpath(Locators.Quantity).click()
        time.sleep(2)
        self.driver.find_element_by_xpath(Locators.DAWCheckbox).click()
        time.sleep(2)
        instruction = self.driver.find_element_by_xpath(Locators.productInstruction)
        instruction.click()
        instruction.send_keys(datasheet.cell(2, 9).value)
        self.driver.find_element_by_xpath(Locators.allergiesButton).click()
        allergies = self.driver.find_element_by_xpath(Locators.allergiesTextbox)
        allergies.clear()
        allergies.send_keys(datasheet.cell(2, 10).value)
        self.driver.find_element_by_xpath(Locators.doneButton).click()
        self.driver.find_element_by_xpath(Locators.addDropchartButton).click()
        time.sleep(2)
        element = self.driver.find_element_by_xpath(Locators.selectDocuments)
        self.driver.execute_script("arguments[0].click()", element)
        self.driver.find_element_by_xpath(Locators.selectButton).click()
        self.driver.find_element_by_xpath(Locators.skipPayment).click()
        self.driver.find_element_by_xpath(Locators.surgeryDate).send_keys(currentDate)
        self.driver.find_element_by_xpath(Locators.pharmacyNotes).send_keys(datasheet.cell(2, 11).value)
        self.driver.find_element_by_xpath(Locators.submit_CreateOrderButton).click()
        time.sleep(7)

    def OnetimeOTCSkipPayment(self):
        self.driver.find_element_by_class_name(Locators.Add_RX).click()
        PatientSearch = self.driver.find_element_by_xpath(Locators.Patient_search_textbox)
        PatientSearch.click()
        PatientSearch.send_keys(datasheet.cell(2, 1).value)
        self.driver.find_element_by_xpath("(//*[text()='" + datasheet.cell(2, 2).value + "'])[1]").click()
        DoctorSearch = self.driver.find_element_by_xpath(Locators.doctor_search_textbox)
        DoctorSearch.click()
        DoctorSearch.send_keys(datasheet.cell(2, 4).value)
        self.driver.find_element_by_xpath("(//*[text()='" + datasheet.cell(2, 4).value + " " + "Practice'])[2]").click()
        self.driver.find_element_by_xpath(Locators.NextButton).click()
        self.driver.find_element_by_xpath(Locators.CreateOnetimeRXButton).click()
        self.driver.find_element_by_name(Locators.OnetimeSearchMedicine).click()
        time.sleep(3)
        Product = self.driver.find_element_by_xpath("//*[text()='" + datasheet.cell(2, 7).value + "']")
        Product.click()
        self.driver.find_element_by_xpath(Locators.AddButton).click()
        self.driver.find_element_by_xpath(Locators.ProductQuantity).click()
        time.sleep(1)
        self.driver.find_element_by_xpath(Locators.Quantity).click()
        self.driver.find_element_by_xpath(Locators.ProductRefilles).click()
        time.sleep(1)
        self.driver.find_element_by_xpath(Locators.Quantity).click()
        time.sleep(2)
        self.driver.find_element_by_xpath(Locators.DAWCheckbox).click()
        time.sleep(2)
        instruction = self.driver.find_element_by_xpath(Locators.productInstruction)
        instruction.click()
        instruction.send_keys(datasheet.cell(2, 9).value)
        self.driver.find_element_by_xpath(Locators.allergiesButton).click()
        allergies = self.driver.find_element_by_xpath(Locators.allergiesTextbox)
        allergies.clear()
        allergies.send_keys(datasheet.cell(2, 10).value)
        self.driver.find_element_by_xpath(Locators.doneButton).click()
        self.driver.find_element_by_xpath(Locators.addDropchartButton).click()
        time.sleep(2)
        element = self.driver.find_element_by_xpath(Locators.selectDocuments)
        self.driver.execute_script("arguments[0].click()", element)
        self.driver.find_element_by_xpath(Locators.selectButton).click()
        self.driver.find_element_by_xpath(Locators.skipPayment).click()
        self.driver.find_element_by_xpath(Locators.surgeryDate).send_keys(currentDate)
        self.driver.find_element_by_xpath(Locators.pharmacyNotes).send_keys(datasheet.cell(2, 11).value)
        self.driver.find_element_by_xpath(Locators.submit_CreateOrderButton).click()
        time.sleep(7)

    def OnetimeCompoundSkipPayment(self):
        self.driver.find_element_by_class_name(Locators.Add_RX).click()
        PatientSearch = self.driver.find_element_by_xpath(Locators.Patient_search_textbox)
        PatientSearch.click()
        PatientSearch.send_keys(datasheet.cell(2, 1).value)
        self.driver.find_element_by_xpath("(//*[text()='" + datasheet.cell(2, 2).value + "'])[1]").click()
        DoctorSearch = self.driver.find_element_by_xpath(Locators.doctor_search_textbox)
        DoctorSearch.click()
        DoctorSearch.send_keys(datasheet.cell(2, 4).value)
        self.driver.find_element_by_xpath("(//*[text()='" + datasheet.cell(2, 4).value + " " + "Practice'])[2]").click()
        self.driver.find_element_by_xpath(Locators.NextButton).click()
        self.driver.find_element_by_xpath(Locators.CreateOnetimeRXButton).click()
        self.driver.find_element_by_name(Locators.OnetimeSearchMedicine).click()
        time.sleep(3)
        Product = self.driver.find_element_by_xpath("//*[text()='" + datasheet.cell(2, 8).value + "']")
        Product.click()
        self.driver.find_element_by_xpath(Locators.AddButton).click()
        self.driver.find_element_by_xpath(Locators.ProductQuantity).click()
        time.sleep(1)
        self.driver.find_element_by_xpath(Locators.Quantity).click()
        self.driver.find_element_by_xpath(Locators.ProductRefilles).click()
        time.sleep(1)
        self.driver.find_element_by_xpath(Locators.Quantity).click()
        time.sleep(2)
        self.driver.find_element_by_xpath(Locators.DAWCheckbox).click()
        time.sleep(2)
        instruction = self.driver.find_element_by_xpath(Locators.productInstruction)
        instruction.click()
        instruction.send_keys(datasheet.cell(2, 9).value)
        self.driver.find_element_by_xpath(Locators.allergiesButton).click()
        allergies = self.driver.find_element_by_xpath(Locators.allergiesTextbox)
        allergies.clear()
        allergies.send_keys(datasheet.cell(2, 10).value)
        self.driver.find_element_by_xpath(Locators.doneButton).click()
        self.driver.find_element_by_xpath(Locators.addDropchartButton).click()
        time.sleep(2)
        element = self.driver.find_element_by_xpath(Locators.selectDocuments)
        self.driver.execute_script("arguments[0].click()", element)
        self.driver.find_element_by_xpath(Locators.selectButton).click()
        self.driver.find_element_by_xpath(Locators.skipPayment).click()
        self.driver.find_element_by_xpath(Locators.surgeryDate).send_keys(currentDate)
        self.driver.find_element_by_xpath(Locators.pharmacyNotes).send_keys(datasheet.cell(2, 11).value)
        self.driver.find_element_by_xpath(Locators.submit_CreateOrderButton).click()
        time.sleep(7)

    def SubscriptionRXSkipPayment(self):
        self.driver.find_element_by_class_name(Locators.Add_RX).click()
        PatientSearch = self.driver.find_element_by_xpath(Locators.Patient_search_textbox)
        PatientSearch.click()
        PatientSearch.send_keys(datasheet.cell(2, 1).value)
        self.driver.find_element_by_xpath("(//*[text()='" + datasheet.cell(2, 2).value + "'])[1]").click()
        DoctorSearch = self.driver.find_element_by_xpath(Locators.doctor_search_textbox)
        DoctorSearch.click()
        DoctorSearch.send_keys(datasheet.cell(2, 4).value)
        self.driver.find_element_by_xpath("(//*[text()='" + datasheet.cell(2, 4).value + " " + "Practice'])[2]").click()
        self.driver.find_element_by_xpath(Locators.NextButton).click()
        el = self.driver.find_element_by_xpath(Locators.createSubscriptionRxButton)
        self.driver.execute_script('arguments[0].click()', el)
        self.driver.find_element_by_xpath(Locators.subscriptionProductSearch).click()
        time.sleep(3)
        Product = self.driver.find_element_by_xpath("//*[text()='" + datasheet.cell(2, 6).value + "']")
        Product.click()
        self.driver.find_element_by_xpath(Locators.AddButton).click()
        self.driver.find_element_by_xpath(Locators.ProductQuantity).click()
        time.sleep(1)
        self.driver.find_element_by_xpath(Locators.Quantity).click()
        self.driver.find_element_by_xpath(Locators.ProductRefilles).click()
        time.sleep(1)
        self.driver.find_element_by_xpath(Locators.Quantity).click()
        time.sleep(2)
        self.driver.find_element_by_xpath(Locators.DAWCheckbox).click()
        time.sleep(2)
        instruction = self.driver.find_element_by_xpath(Locators.productInstruction)
        instruction.click()
        instruction.send_keys(datasheet.cell(2, 9).value)
        self.driver.find_element_by_xpath(Locators.allergiesButton).click()
        allergies = self.driver.find_element_by_xpath(Locators.allergiesTextbox)
        allergies.clear()
        allergies.send_keys(datasheet.cell(2, 10).value)
        self.driver.find_element_by_xpath(Locators.doneButton).click()
        self.driver.find_element_by_xpath(Locators.addDropchartButton).click()
        time.sleep(2)
        element = self.driver.find_element_by_xpath(Locators.selectDocuments)
        self.driver.execute_script("arguments[0].click()", element)
        self.driver.find_element_by_xpath(Locators.selectButton).click()
        self.driver.find_element_by_xpath(Locators.skipPayment).click()
        self.driver.find_element_by_xpath(Locators.surgeryDate).send_keys(currentDate)
        self.driver.find_element_by_xpath(Locators.pharmacyNotes).send_keys(datasheet.cell(2, 11).value)
        self.driver.find_element_by_xpath(Locators.submit_CreateOrderButton).click()
        time.sleep(7)

    def SubscriptionOTCSkipPayment(self):
        self.driver.find_element_by_class_name(Locators.Add_RX).click()
        PatientSearch = self.driver.find_element_by_xpath(Locators.Patient_search_textbox)
        PatientSearch.click()
        PatientSearch.send_keys(datasheet.cell(2, 1).value)
        self.driver.find_element_by_xpath("(//*[text()='" + datasheet.cell(2, 2).value + "'])[1]").click()
        DoctorSearch = self.driver.find_element_by_xpath(Locators.doctor_search_textbox)
        DoctorSearch.click()
        DoctorSearch.send_keys(datasheet.cell(2, 4).value)
        self.driver.find_element_by_xpath("(//*[text()='" + datasheet.cell(2, 4).value + " " + "Practice'])[2]").click()
        self.driver.find_element_by_xpath(Locators.NextButton).click()
        el = self.driver.find_element_by_xpath(Locators.createSubscriptionRxButton)
        self.driver.execute_script('arguments[0].click()', el)
        self.driver.find_element_by_xpath(Locators.subscriptionProductSearch).click()
        time.sleep(3)
        Product = self.driver.find_element_by_xpath("//*[text()='" + datasheet.cell(2, 7).value + "']")
        Product.click()
        self.driver.find_element_by_xpath(Locators.AddButton).click()
        self.driver.find_element_by_xpath(Locators.ProductQuantity).click()
        time.sleep(1)
        self.driver.find_element_by_xpath(Locators.Quantity).click()
        self.driver.find_element_by_xpath(Locators.ProductRefilles).click()
        time.sleep(1)
        self.driver.find_element_by_xpath(Locators.Quantity).click()
        time.sleep(2)
        self.driver.find_element_by_xpath(Locators.DAWCheckbox).click()
        time.sleep(2)
        instruction = self.driver.find_element_by_xpath(Locators.productInstruction)
        instruction.click()
        instruction.send_keys(datasheet.cell(2, 9).value)
        self.driver.find_element_by_xpath(Locators.allergiesButton).click()
        allergies = self.driver.find_element_by_xpath(Locators.allergiesTextbox)
        allergies.clear()
        allergies.send_keys(datasheet.cell(2, 10).value)
        self.driver.find_element_by_xpath(Locators.doneButton).click()
        self.driver.find_element_by_xpath(Locators.addDropchartButton).click()
        time.sleep(2)
        element = self.driver.find_element_by_xpath(Locators.selectDocuments)
        self.driver.execute_script("arguments[0].click()", element)
        self.driver.find_element_by_xpath(Locators.selectButton).click()
        self.driver.find_element_by_xpath(Locators.skipPayment).click()
        self.driver.find_element_by_xpath(Locators.surgeryDate).send_keys(currentDate)
        self.driver.find_element_by_xpath(Locators.pharmacyNotes).send_keys(datasheet.cell(2, 11).value)
        self.driver.find_element_by_xpath(Locators.submit_CreateOrderButton).click()
        time.sleep(7)

    def SubscriptionCompoundSkipPayment(self):
        self.driver.find_element_by_class_name(Locators.Add_RX).click()
        PatientSearch = self.driver.find_element_by_xpath(Locators.Patient_search_textbox)
        PatientSearch.click()
        PatientSearch.send_keys(datasheet.cell(2, 1).value)
        self.driver.find_element_by_xpath("(//*[text()='" + datasheet.cell(2, 2).value + "'])[1]").click()
        DoctorSearch = self.driver.find_element_by_xpath(Locators.doctor_search_textbox)
        DoctorSearch.click()
        DoctorSearch.send_keys(datasheet.cell(2, 4).value)
        self.driver.find_element_by_xpath("(//*[text()='" + datasheet.cell(2, 4).value + " " + "Practice'])[2]").click()
        self.driver.find_element_by_xpath(Locators.NextButton).click()
        el = self.driver.find_element_by_xpath(Locators.createSubscriptionRxButton)
        self.driver.execute_script('arguments[0].click()', el)
        self.driver.find_element_by_xpath(Locators.subscriptionProductSearch).click()
        time.sleep(3)
        Product = self.driver.find_element_by_xpath("//*[text()='" + datasheet.cell(2, 8).value + "']")
        Product.click()
        self.driver.find_element_by_xpath(Locators.AddButton).click()
        self.driver.find_element_by_xpath(Locators.ProductQuantity).click()
        time.sleep(1)
        self.driver.find_element_by_xpath(Locators.Quantity).click()
        self.driver.find_element_by_xpath(Locators.ProductRefilles).click()
        time.sleep(1)
        self.driver.find_element_by_xpath(Locators.Quantity).click()
        time.sleep(2)
        self.driver.find_element_by_xpath(Locators.DAWCheckbox).click()
        time.sleep(2)
        instruction = self.driver.find_element_by_xpath(Locators.productInstruction)
        instruction.click()
        instruction.send_keys(datasheet.cell(2, 9).value)
        self.driver.find_element_by_xpath(Locators.allergiesButton).click()
        allergies = self.driver.find_element_by_xpath(Locators.allergiesTextbox)
        allergies.clear()
        allergies.send_keys(datasheet.cell(2, 10).value)
        self.driver.find_element_by_xpath(Locators.doneButton).click()
        self.driver.find_element_by_xpath(Locators.addDropchartButton).click()
        time.sleep(2)
        element = self.driver.find_element_by_xpath(Locators.selectDocuments)
        self.driver.execute_script("arguments[0].click()", element)
        self.driver.find_element_by_xpath(Locators.selectButton).click()
        self.driver.find_element_by_xpath(Locators.skipPayment).click()
        self.driver.find_element_by_xpath(Locators.surgeryDate).send_keys(currentDate)
        self.driver.find_element_by_xpath(Locators.pharmacyNotes).send_keys(datasheet.cell(2, 11).value)
        self.driver.find_element_by_xpath(Locators.submit_CreateOrderButton).click()
        time.sleep(7)

    def OnetimeRXProvidePayment(self):
        self.driver.find_element_by_class_name(Locators.Add_RX).click()
        PatientSearch = self.driver.find_element_by_xpath(Locators.Patient_search_textbox)
        PatientSearch.click()
        PatientSearch.send_keys(datasheet.cell(2, 1).value)
        self.driver.find_element_by_xpath("(//*[text()='" + datasheet.cell(2, 2).value + "'])[1]").click()
        DoctorSearch = self.driver.find_element_by_xpath(Locators.doctor_search_textbox)
        DoctorSearch.click()
        DoctorSearch.send_keys(datasheet.cell(2, 4).value)
        self.driver.find_element_by_xpath("(//*[text()='" + datasheet.cell(2, 4).value + " " + "Practice'])[2]").click()
        self.driver.find_element_by_xpath(Locators.NextButton).click()
        self.driver.find_element_by_xpath(Locators.CreateOnetimeRXButton).click()
        self.driver.find_element_by_name(Locators.OnetimeSearchMedicine).click()
        time.sleep(3)
        Product = self.driver.find_element_by_xpath("//*[text()='" + datasheet.cell(2, 6).value + "']")
        Product.click()
        self.driver.find_element_by_xpath(Locators.AddButton).click()
        self.driver.find_element_by_xpath(Locators.ProductQuantity).click()
        time.sleep(1)
        self.driver.find_element_by_xpath(Locators.Quantity).click()
        self.driver.find_element_by_xpath(Locators.ProductRefilles).click()
        time.sleep(1)
        self.driver.find_element_by_xpath(Locators.Quantity).click()
        time.sleep(2)
        self.driver.find_element_by_xpath(Locators.DAWCheckbox).click()
        time.sleep(2)
        instruction = self.driver.find_element_by_xpath(Locators.productInstruction)
        instruction.click()
        instruction.send_keys(datasheet.cell(2, 9).value)
        self.driver.find_element_by_xpath(Locators.allergiesButton).click()
        allergies = self.driver.find_element_by_xpath(Locators.allergiesTextbox)
        allergies.clear()
        allergies.send_keys(datasheet.cell(2, 10).value)
        self.driver.find_element_by_xpath(Locators.doneButton).click()
        self.driver.find_element_by_xpath(Locators.addDropchartButton).click()
        time.sleep(2)
        element = self.driver.find_element_by_xpath(Locators.selectDocuments)
        self.driver.execute_script("arguments[0].click()", element)
        self.driver.find_element_by_xpath(Locators.selectButton).click()
        self.driver.find_element_by_xpath(Locators.providePayment).click()
        cardname = self.driver.find_element_by_name(Locators.cardName)
        cardname.clear()
        cardname.send_keys(datasheet.cell(2, 13).value)
        cardNumber = self.driver.find_element_by_name(Locators.cardNumber)
        cardNumber.clear()
        cardNumber.send_keys(datasheet.cell(2, 14).value)
        self.driver.find_element_by_xpath(Locators.cardMonthDropdown).click()
        time.sleep(1)
        self.driver.find_element_by_xpath(Locators.cardMonth).click()
        time.sleep(1)
        self.driver.find_element_by_xpath(Locators.cardYearDropdown).click()
        time.sleep(1)
        self.driver.find_element_by_xpath(Locators.cardYear).click()
        cardCVV = self.driver.find_element_by_name(Locators.cardCVV)
        cardCVV.clear()
        cardCVV.send_keys(datasheet.cell(2, 15).value)
        Address1 = self.driver.find_element_by_name(Locators.addressLine1)
        Address1.clear()
        Address1.send_keys(datasheet.cell(2, 18).value)
        address2 = self.driver.find_element_by_name(Locators.addressLine2)
        address2.clear()
        address2.send_keys(datasheet.cell(2, 19).value)
        addressCity = self.driver.find_element_by_name(Locators.addressCity)
        addressCity.clear()
        addressCity.send_keys(datasheet.cell(2, 20).value)
        self.driver.find_element_by_xpath(Locators.addressState).click()
        time.sleep(2)
        self.driver.find_element_by_xpath(Locators.state).click()
        time.sleep(7)
        addressZipcode = self.driver.find_element_by_name(Locators.addressZipCode)
        addressZipcode.clear()
        addressZipcode.send_keys(datasheet.cell(2, 22).value)
        self.driver.find_element_by_xpath(Locators.continueButton).click()
        self.driver.find_element_by_xpath(Locators.surgeryDate).send_keys(currentDate)
        notes = self.driver.find_element_by_xpath(Locators.pharmacyNotes)
        notes.clear()
        notes.send_keys(datasheet.cell(2, 11).value)
        self.driver.find_element_by_xpath(Locators.submit_CreateOrderButton).click()
        time.sleep(7)

    def OnetimeOTCProvidePayment(self):
        self.driver.find_element_by_class_name(Locators.Add_RX).click()
        PatientSearch = self.driver.find_element_by_xpath(Locators.Patient_search_textbox)
        PatientSearch.click()
        PatientSearch.send_keys(datasheet.cell(2, 1).value)
        self.driver.find_element_by_xpath("(//*[text()='" + datasheet.cell(2, 2).value + "'])[1]").click()
        DoctorSearch = self.driver.find_element_by_xpath(Locators.doctor_search_textbox)
        DoctorSearch.click()
        DoctorSearch.send_keys(datasheet.cell(2, 4).value)
        self.driver.find_element_by_xpath("(//*[text()='" + datasheet.cell(2, 4).value + " " + "Practice'])[2]").click()
        self.driver.find_element_by_xpath(Locators.NextButton).click()
        self.driver.find_element_by_xpath(Locators.CreateOnetimeRXButton).click()
        self.driver.find_element_by_name(Locators.OnetimeSearchMedicine).click()
        time.sleep(3)
        Product = self.driver.find_element_by_xpath("//*[text()='" + datasheet.cell(2, 7).value + "']")
        Product.click()
        self.driver.find_element_by_xpath(Locators.AddButton).click()
        self.driver.find_element_by_xpath(Locators.ProductQuantity).click()
        time.sleep(1)
        self.driver.find_element_by_xpath(Locators.Quantity).click()
        self.driver.find_element_by_xpath(Locators.ProductRefilles).click()
        time.sleep(1)
        self.driver.find_element_by_xpath(Locators.Quantity).click()
        time.sleep(2)
        self.driver.find_element_by_xpath(Locators.DAWCheckbox).click()
        time.sleep(2)
        instruction = self.driver.find_element_by_xpath(Locators.productInstruction)
        instruction.click()
        instruction.send_keys(datasheet.cell(2, 9).value)
        self.driver.find_element_by_xpath(Locators.allergiesButton).click()
        allergies = self.driver.find_element_by_xpath(Locators.allergiesTextbox)
        allergies.clear()
        allergies.send_keys(datasheet.cell(2, 10).value)
        self.driver.find_element_by_xpath(Locators.doneButton).click()
        self.driver.find_element_by_xpath(Locators.addDropchartButton).click()
        time.sleep(2)
        element = self.driver.find_element_by_xpath(Locators.selectDocuments)
        self.driver.execute_script("arguments[0].click()", element)
        self.driver.find_element_by_xpath(Locators.selectButton).click()
        self.driver.find_element_by_xpath(Locators.providePayment).click()
        cardname = self.driver.find_element_by_name(Locators.cardName)
        cardname.clear()
        cardname.send_keys(datasheet.cell(2, 13).value)
        cardNumber = self.driver.find_element_by_name(Locators.cardNumber)
        cardNumber.clear()
        cardNumber.send_keys(datasheet.cell(2, 14).value)
        self.driver.find_element_by_xpath(Locators.cardMonthDropdown).click()
        time.sleep(1)
        self.driver.find_element_by_xpath(Locators.cardMonth).click()
        time.sleep(1)
        self.driver.find_element_by_xpath(Locators.cardYearDropdown).click()
        time.sleep(1)
        self.driver.find_element_by_xpath(Locators.cardYear).click()
        cardCVV = self.driver.find_element_by_name(Locators.cardCVV)
        cardCVV.clear()
        cardCVV.send_keys(datasheet.cell(2, 15).value)
        Address1 = self.driver.find_element_by_name(Locators.addressLine1)
        Address1.clear()
        Address1.send_keys(datasheet.cell(2, 18).value)
        address2 = self.driver.find_element_by_name(Locators.addressLine2)
        address2.clear()
        address2.send_keys(datasheet.cell(2, 19).value)
        addressCity = self.driver.find_element_by_name(Locators.addressCity)
        addressCity.clear()
        addressCity.send_keys(datasheet.cell(2, 20).value)
        self.driver.find_element_by_xpath(Locators.addressState).click()
        time.sleep(2)
        self.driver.find_element_by_xpath(Locators.state).click()
        addressZipcode = self.driver.find_element_by_name(Locators.addressZipCode)
        addressZipcode.clear()
        addressZipcode.send_keys(datasheet.cell(2, 22).value)
        self.driver.find_element_by_xpath(Locators.continueButton).click()
        self.driver.find_element_by_xpath(Locators.surgeryDate).send_keys(currentDate)
        notes = self.driver.find_element_by_xpath(Locators.pharmacyNotes)
        notes.clear()
        notes.send_keys(datasheet.cell(2, 11).value)
        self.driver.find_element_by_xpath(Locators.submit_CreateOrderButton).click()
        time.sleep(7)

    def OnetimeCompoundProvidePayment(self):
        self.driver.find_element_by_class_name(Locators.Add_RX).click()
        PatientSearch = self.driver.find_element_by_xpath(Locators.Patient_search_textbox)
        PatientSearch.click()
        PatientSearch.send_keys(datasheet.cell(2, 1).value)
        self.driver.find_element_by_xpath("(//*[text()='" + datasheet.cell(2, 2).value + "'])[1]").click()
        DoctorSearch = self.driver.find_element_by_xpath(Locators.doctor_search_textbox)
        DoctorSearch.click()
        DoctorSearch.send_keys(datasheet.cell(2, 4).value)
        self.driver.find_element_by_xpath("(//*[text()='" + datasheet.cell(2, 4).value + " " + "Practice'])[2]").click()
        self.driver.find_element_by_xpath(Locators.NextButton).click()
        self.driver.find_element_by_xpath(Locators.CreateOnetimeRXButton).click()
        self.driver.find_element_by_name(Locators.OnetimeSearchMedicine).click()
        time.sleep(3)
        Product = self.driver.find_element_by_xpath("//*[text()='" + datasheet.cell(2, 8).value + "']")
        Product.click()
        self.driver.find_element_by_xpath(Locators.AddButton).click()
        self.driver.find_element_by_xpath(Locators.ProductQuantity).click()
        time.sleep(1)
        self.driver.find_element_by_xpath(Locators.Quantity).click()
        self.driver.find_element_by_xpath(Locators.ProductRefilles).click()
        time.sleep(1)
        self.driver.find_element_by_xpath(Locators.Quantity).click()
        time.sleep(2)
        self.driver.find_element_by_xpath(Locators.DAWCheckbox).click()
        time.sleep(2)
        instruction = self.driver.find_element_by_xpath(Locators.productInstruction)
        instruction.click()
        instruction.send_keys(datasheet.cell(2, 9).value)
        self.driver.find_element_by_xpath(Locators.allergiesButton).click()
        allergies = self.driver.find_element_by_xpath(Locators.allergiesTextbox)
        allergies.clear()
        allergies.send_keys(datasheet.cell(2, 10).value)
        self.driver.find_element_by_xpath(Locators.doneButton).click()
        self.driver.find_element_by_xpath(Locators.addDropchartButton).click()
        time.sleep(2)
        element = self.driver.find_element_by_xpath(Locators.selectDocuments)
        self.driver.execute_script("arguments[0].click()", element)
        self.driver.find_element_by_xpath(Locators.selectButton).click()
        self.driver.find_element_by_xpath(Locators.providePayment).click()
        cardname = self.driver.find_element_by_name(Locators.cardName)
        cardname.clear()
        cardname.send_keys(datasheet.cell(2, 13).value)
        cardNumber = self.driver.find_element_by_name(Locators.cardNumber)
        cardNumber.clear()
        cardNumber.send_keys(datasheet.cell(2, 14).value)
        self.driver.find_element_by_xpath(Locators.cardMonthDropdown).click()
        time.sleep(1)
        self.driver.find_element_by_xpath(Locators.cardMonth).click()
        time.sleep(1)
        self.driver.find_element_by_xpath(Locators.cardYearDropdown).click()
        time.sleep(1)
        self.driver.find_element_by_xpath(Locators.cardYear).click()
        cardCVV = self.driver.find_element_by_name(Locators.cardCVV)
        cardCVV.clear()
        cardCVV.send_keys(datasheet.cell(2, 15).value)
        Address1 = self.driver.find_element_by_name(Locators.addressLine1)
        Address1.clear()
        Address1.send_keys(datasheet.cell(2, 18).value)
        address2 = self.driver.find_element_by_name(Locators.addressLine2)
        address2.clear()
        address2.send_keys(datasheet.cell(2, 19).value)
        addressCity = self.driver.find_element_by_name(Locators.addressCity)
        addressCity.clear()
        addressCity.send_keys(datasheet.cell(2, 20).value)
        self.driver.find_element_by_xpath(Locators.addressState).click()
        time.sleep(2)
        self.driver.find_element_by_xpath(Locators.state).click()
        addressZipcode = self.driver.find_element_by_name(Locators.addressZipCode)
        addressZipcode.clear()
        addressZipcode.send_keys(datasheet.cell(2, 22).value)
        self.driver.find_element_by_xpath(Locators.continueButton).click()
        self.driver.find_element_by_xpath(Locators.surgeryDate).send_keys(currentDate)
        notes = self.driver.find_element_by_xpath(Locators.pharmacyNotes)
        notes.clear()
        notes.send_keys(datasheet.cell(2, 11).value)
        self.driver.find_element_by_xpath(Locators.submit_CreateOrderButton).click()
        time.sleep(7)

    def SubscriptionRXProvidePayment(self):
        self.driver.find_element_by_class_name(Locators.Add_RX).click()
        PatientSearch = self.driver.find_element_by_xpath(Locators.Patient_search_textbox)
        PatientSearch.click()
        PatientSearch.send_keys(datasheet.cell(2, 1).value)
        self.driver.find_element_by_xpath("(//*[text()='" + datasheet.cell(2, 2).value + "'])[1]").click()
        DoctorSearch = self.driver.find_element_by_xpath(Locators.doctor_search_textbox)
        DoctorSearch.click()
        DoctorSearch.send_keys(datasheet.cell(2, 4).value)
        self.driver.find_element_by_xpath("(//*[text()='" + datasheet.cell(2, 4).value + " " + "Practice'])[2]").click()
        self.driver.find_element_by_xpath(Locators.NextButton).click()
        time.sleep(2)
        el = self.driver.find_element_by_xpath(Locators.createSubscriptionRxButton)
        self.driver.execute_script('arguments[0].click()', el)
        self.driver.find_element_by_xpath(Locators.subscriptionProductSearch).click()
        time.sleep(3)
        Product = self.driver.find_element_by_xpath("//*[text()='" + datasheet.cell(2, 6).value + "']")
        Product.click()
        self.driver.find_element_by_xpath(Locators.AddButton).click()
        self.driver.find_element_by_xpath(Locators.ProductQuantity).click()
        time.sleep(1)
        self.driver.find_element_by_xpath(Locators.Quantity).click()
        self.driver.find_element_by_xpath(Locators.ProductRefilles).click()
        time.sleep(1)
        self.driver.find_element_by_xpath(Locators.Quantity).click()
        time.sleep(2)
        self.driver.find_element_by_xpath(Locators.DAWCheckbox).click()
        time.sleep(2)
        instruction = self.driver.find_element_by_xpath(Locators.productInstruction)
        instruction.click()
        instruction.send_keys(datasheet.cell(2, 9).value)
        self.driver.find_element_by_xpath(Locators.allergiesButton).click()
        allergies = self.driver.find_element_by_xpath(Locators.allergiesTextbox)
        allergies.clear()
        allergies.send_keys(datasheet.cell(2, 10).value)
        self.driver.find_element_by_xpath(Locators.doneButton).click()
        self.driver.find_element_by_xpath(Locators.addDropchartButton).click()
        time.sleep(2)
        element = self.driver.find_element_by_xpath(Locators.selectDocuments)
        self.driver.execute_script("arguments[0].click()", element)
        self.driver.find_element_by_xpath(Locators.selectButton).click()
        self.driver.find_element_by_xpath(Locators.providePayment).click()
        cardname = self.driver.find_element_by_name(Locators.cardName)
        cardname.clear()
        cardname.send_keys(datasheet.cell(2, 13).value)
        cardNumber = self.driver.find_element_by_name(Locators.cardNumber)
        cardNumber.clear()
        cardNumber.send_keys(datasheet.cell(2, 14).value)
        self.driver.find_element_by_xpath(Locators.cardMonthDropdown).click()
        time.sleep(1)
        self.driver.find_element_by_xpath(Locators.cardMonth).click()
        time.sleep(1)
        self.driver.find_element_by_xpath(Locators.cardYearDropdown).click()
        time.sleep(1)
        self.driver.find_element_by_xpath(Locators.cardYear).click()
        cardCVV = self.driver.find_element_by_name(Locators.cardCVV)
        cardCVV.clear()
        cardCVV.send_keys(datasheet.cell(2, 15).value)
        Address1 = self.driver.find_element_by_name(Locators.addressLine1)
        Address1.clear()
        Address1.send_keys(datasheet.cell(2, 18).value)
        address2 = self.driver.find_element_by_name(Locators.addressLine2)
        address2.clear()
        address2.send_keys(datasheet.cell(2, 19).value)
        addressCity = self.driver.find_element_by_name(Locators.addressCity)
        addressCity.clear()
        addressCity.send_keys(datasheet.cell(2, 20).value)
        self.driver.find_element_by_xpath(Locators.addressState).click()
        time.sleep(2)
        self.driver.find_element_by_xpath(Locators.state).click()
        addressZipcode = self.driver.find_element_by_name(Locators.addressZipCode)
        addressZipcode.clear()
        addressZipcode.send_keys(datasheet.cell(2, 22).value)
        self.driver.find_element_by_xpath(Locators.continueButton).click()
        self.driver.find_element_by_xpath(Locators.surgeryDate).send_keys(currentDate)
        notes = self.driver.find_element_by_xpath(Locators.pharmacyNotes)
        notes.clear()
        notes.send_keys(datasheet.cell(2, 11).value)
        self.driver.find_element_by_xpath(Locators.submit_CreateOrderButton).click()
        time.sleep(7)

    def SubscriptionOTCProvidePayment(self):
        self.driver.find_element_by_class_name(Locators.Add_RX).click()
        PatientSearch = self.driver.find_element_by_xpath(Locators.Patient_search_textbox)
        PatientSearch.click()
        PatientSearch.send_keys(datasheet.cell(2, 1).value)
        self.driver.find_element_by_xpath("(//*[text()='" + datasheet.cell(2, 2).value + "'])[1]").click()
        DoctorSearch = self.driver.find_element_by_xpath(Locators.doctor_search_textbox)
        DoctorSearch.click()
        DoctorSearch.send_keys(datasheet.cell(2, 4).value)
        self.driver.find_element_by_xpath("(//*[text()='" + datasheet.cell(2, 4).value + " " + "Practice'])[2]").click()
        self.driver.find_element_by_xpath(Locators.NextButton).click()
        time.sleep(2)
        el = self.driver.find_element_by_xpath(Locators.createSubscriptionRxButton)
        self.driver.execute_script('arguments[0].click()', el)
        self.driver.find_element_by_xpath(Locators.subscriptionProductSearch).click()
        time.sleep(3)
        Product = self.driver.find_element_by_xpath("//*[text()='" + datasheet.cell(2, 7).value + "']")
        Product.click()
        self.driver.find_element_by_xpath(Locators.AddButton).click()
        self.driver.find_element_by_xpath(Locators.ProductQuantity).click()
        time.sleep(1)
        self.driver.find_element_by_xpath(Locators.Quantity).click()
        self.driver.find_element_by_xpath(Locators.ProductRefilles).click()
        time.sleep(1)
        self.driver.find_element_by_xpath(Locators.Quantity).click()
        time.sleep(2)
        self.driver.find_element_by_xpath(Locators.DAWCheckbox).click()
        time.sleep(2)
        instruction = self.driver.find_element_by_xpath(Locators.productInstruction)
        instruction.click()
        instruction.send_keys(datasheet.cell(2, 9).value)
        self.driver.find_element_by_xpath(Locators.allergiesButton).click()
        allergies = self.driver.find_element_by_xpath(Locators.allergiesTextbox)
        allergies.clear()
        allergies.send_keys(datasheet.cell(2, 10).value)
        self.driver.find_element_by_xpath(Locators.doneButton).click()
        self.driver.find_element_by_xpath(Locators.addDropchartButton).click()
        time.sleep(2)
        element = self.driver.find_element_by_xpath(Locators.selectDocuments)
        self.driver.execute_script("arguments[0].click()", element)
        self.driver.find_element_by_xpath(Locators.selectButton).click()
        self.driver.find_element_by_xpath(Locators.providePayment).click()
        cardname = self.driver.find_element_by_name(Locators.cardName)
        cardname.clear()
        cardname.send_keys(datasheet.cell(2, 13).value)
        cardNumber = self.driver.find_element_by_name(Locators.cardNumber)
        cardNumber.clear()
        cardNumber.send_keys(datasheet.cell(2, 14).value)
        self.driver.find_element_by_xpath(Locators.cardMonthDropdown).click()
        time.sleep(1)
        self.driver.find_element_by_xpath(Locators.cardMonth).click()
        time.sleep(1)
        self.driver.find_element_by_xpath(Locators.cardYearDropdown).click()
        time.sleep(1)
        self.driver.find_element_by_xpath(Locators.cardYear).click()
        cardCVV = self.driver.find_element_by_name(Locators.cardCVV)
        cardCVV.clear()
        cardCVV.send_keys(datasheet.cell(2, 15).value)
        Address1 = self.driver.find_element_by_name(Locators.addressLine1)
        Address1.clear()
        Address1.send_keys(datasheet.cell(2, 18).value)
        address2 = self.driver.find_element_by_name(Locators.addressLine2)
        address2.clear()
        address2.send_keys(datasheet.cell(2, 19).value)
        addressCity = self.driver.find_element_by_name(Locators.addressCity)
        addressCity.clear()
        addressCity.send_keys(datasheet.cell(2, 20).value)
        self.driver.find_element_by_xpath(Locators.addressState).click()
        time.sleep(2)
        self.driver.find_element_by_xpath(Locators.state).click()
        addressZipcode = self.driver.find_element_by_name(Locators.addressZipCode)
        addressZipcode.clear()
        addressZipcode.send_keys(datasheet.cell(2, 22).value)
        self.driver.find_element_by_xpath(Locators.continueButton).click()
        self.driver.find_element_by_xpath(Locators.surgeryDate).send_keys(currentDate)
        notes = self.driver.find_element_by_xpath(Locators.pharmacyNotes)
        notes.clear()
        notes.send_keys(datasheet.cell(2, 11).value)
        self.driver.find_element_by_xpath(Locators.submit_CreateOrderButton).click()
        time.sleep(7)

    def SubscriptionCompoundProvidePayment(self):
        self.driver.find_element_by_class_name(Locators.Add_RX).click()
        PatientSearch = self.driver.find_element_by_xpath(Locators.Patient_search_textbox)
        PatientSearch.click()
        PatientSearch.send_keys(datasheet.cell(2, 1).value)
        self.driver.find_element_by_xpath("(//*[text()='" + datasheet.cell(2, 2).value + "'])[1]").click()
        DoctorSearch = self.driver.find_element_by_xpath(Locators.doctor_search_textbox)
        DoctorSearch.click()
        DoctorSearch.send_keys(datasheet.cell(2, 4).value)
        self.driver.find_element_by_xpath("(//*[text()='" + datasheet.cell(2, 4).value + " " + "Practice'])[2]").click()
        self.driver.find_element_by_xpath(Locators.NextButton).click()
        time.sleep(2)
        el = self.driver.find_element_by_xpath(Locators.createSubscriptionRxButton)
        self.driver.execute_script('arguments[0].click()', el)
        self.driver.find_element_by_xpath(Locators.subscriptionProductSearch).click()
        time.sleep(3)
        Product = self.driver.find_element_by_xpath("//*[text()='" + datasheet.cell(2, 8).value + "']")
        Product.click()
        self.driver.find_element_by_xpath(Locators.AddButton).click()
        self.driver.find_element_by_xpath(Locators.ProductQuantity).click()
        time.sleep(1)
        self.driver.find_element_by_xpath(Locators.Quantity).click()
        self.driver.find_element_by_xpath(Locators.ProductRefilles).click()
        time.sleep(1)
        self.driver.find_element_by_xpath(Locators.Quantity).click()
        time.sleep(2)
        self.driver.find_element_by_xpath(Locators.DAWCheckbox).click()
        time.sleep(2)
        instruction = self.driver.find_element_by_xpath(Locators.productInstruction)
        instruction.click()
        instruction.send_keys(datasheet.cell(2, 9).value)
        self.driver.find_element_by_xpath(Locators.allergiesButton).click()
        allergies = self.driver.find_element_by_xpath(Locators.allergiesTextbox)
        allergies.clear()
        allergies.send_keys(datasheet.cell(2, 10).value)
        self.driver.find_element_by_xpath(Locators.doneButton).click()
        self.driver.find_element_by_xpath(Locators.addDropchartButton).click()
        time.sleep(2)
        element = self.driver.find_element_by_xpath(Locators.selectDocuments)
        self.driver.execute_script("arguments[0].click()", element)
        self.driver.find_element_by_xpath(Locators.selectButton).click()
        self.driver.find_element_by_xpath(Locators.providePayment).click()
        cardname = self.driver.find_element_by_name(Locators.cardName)
        cardname.clear()
        cardname.send_keys(datasheet.cell(2, 13).value)
        cardNumber = self.driver.find_element_by_name(Locators.cardNumber)
        cardNumber.clear()
        cardNumber.send_keys(datasheet.cell(2, 14).value)
        self.driver.find_element_by_xpath(Locators.cardMonthDropdown).click()
        time.sleep(1)
        self.driver.find_element_by_xpath(Locators.cardMonth).click()
        time.sleep(1)
        self.driver.find_element_by_xpath(Locators.cardYearDropdown).click()
        time.sleep(1)
        self.driver.find_element_by_xpath(Locators.cardYear).click()
        cardCVV = self.driver.find_element_by_name(Locators.cardCVV)
        cardCVV.clear()
        cardCVV.send_keys(datasheet.cell(2, 15).value)
        Address1 = self.driver.find_element_by_name(Locators.addressLine1)
        Address1.clear()
        Address1.send_keys(datasheet.cell(2, 18).value)
        address2 = self.driver.find_element_by_name(Locators.addressLine2)
        address2.clear()
        address2.send_keys(datasheet.cell(2, 19).value)
        addressCity = self.driver.find_element_by_name(Locators.addressCity)
        addressCity.clear()
        addressCity.send_keys(datasheet.cell(2, 20).value)
        self.driver.find_element_by_xpath(Locators.addressState).click()
        time.sleep(2)
        self.driver.find_element_by_xpath(Locators.state).click()
        addressZipcode = self.driver.find_element_by_name(Locators.addressZipCode)
        addressZipcode.clear()
        addressZipcode.send_keys(datasheet.cell(2, 22).value)
        self.driver.find_element_by_xpath(Locators.continueButton).click()
        self.driver.find_element_by_xpath(Locators.surgeryDate).send_keys(currentDate)
        notes = self.driver.find_element_by_xpath(Locators.pharmacyNotes)
        notes.clear()
        notes.send_keys(datasheet.cell(2, 11).value)
        self.driver.find_element_by_xpath(Locators.submit_CreateOrderButton).click()
        time.sleep(7)

    def EditOrder(self):
        self.driver.find_element_by_link_text('Orders').click()
        self.driver.find_element_by_xpath('//*[@class="table"]//*[a]').click()
        self.driver.find_element_by_link_text('Edit Contents').click()
        self.driver.find_element_by_xpath('//*[@class="sc-hXRMBi eQtMFe"]').click()
        self.driver.find_element_by_xpath(Locators.searchForMedication).click()
        time.sleep(3)
        self.driver.find_element_by_xpath("//*[text()='150 Rx']").click()
        self.driver.find_element_by_xpath(Locators.AddButton).click()
        time.sleep(1)
        self.driver.find_element_by_xpath(Locators.skipPayment).click()
        self.driver.find_element_by_xpath(Locators.updateOrderButton).click()
        time.sleep(7)
        if "You're all set!" in self.driver.page_source:
            self.driver.find_element_by_partial_link_text("Return to Dashboard").click()
        else:
            print("\nOrder not created")

        self.driver.find_element_by_class_name('account-link-label').click()
        self.driver.find_element_by_link_text('Sign Out').click()
        assert self.driver.current_url == loginSheet.cell(2, 2).value
        time.sleep(1)
        self.driver.close()
