name: Legrande GitHub Actions
on:
#   schedule:
#   - cron: "0 0 * * *"

  push:
    branches:
      - 'master'
      
jobs:
 seleniumPython-test:
  name: Run on Linux
  runs-on: ubuntu-20.04
  steps:
  - uses: actions/checkout@main
  - uses: actions/setup-python@v2
    with:
      python-version: '3.8'
  - run: pip install -r requirements.txt

  - name: Wait for Agent to Register
    run: bash .github/ci/wait_for_agent.sh
  - run: pytest
