name: Legrande GitHub Actions
on:
#   schedule:
#   - cron: "0 0 * * *"

  push:
    branches:
      - 'master'

jobs:
 seleniumPython-test:
  name: Run on Linux
  runs-on: ubuntu-20.04

  steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Test with pytest
      continue-on-error: true
      run: |
        py.test --html=report.html -v testCases/Master.py

    - name: make public directory
      run: |
        mkdir public
        cp -r report.html public/report.html

    - name: download artifact
      uses: actions/upload-artifact@v2
      with:
        name: Download-reports
        path: report.html

    - name: Deploy reports
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
