name: Legrande GitHub Actions
on:
#   schedule:
#   - cron: "0 0 * * *"

  push:
    branches:
      - 'master'
      
jobs:
 seleniumPython-test:
  name: Run on Linux
  runs-on: ubuntu-20.04
  steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Install SeleniumBase
      run: |
        python setup.py install
    - name: Install Chrome
      run: |
        sudo apt install google-chrome-stabl
    - name: Install chromedriver
      run: |
        seleniumbase install chromedriver
    - name: Run pytest verify_framework.py --browser=chrome --headless
      run: |
        py.test --html=report.html -v -s testCases/Master.py
        py.test --html=report.html -v -s testCases/Practice.py
        py.test --html=report.html -v -s testCases/Hub.py
        py.test --html=report.html -v -s testCases/StandardPharma.py
        py.test --html=report.html -v -s testCases/Patient.py